//
//  RegistrationTimetableView.swift
//  CaptionCalendar
//
//  Created by 髙間洋平 on 2021/10/10.
//

import SwiftUI

struct RegistrationTimetableView: View {
    
    
    
    
    @State private var university = "愛媛大学"
    @State private var timetables = ""
    @State private var timetable1 = ""
    @State private var timetable2 = ""
    @State private var courseName = ""
    @State private var teacherName = ""
    @State private var classcode = ""
    @State private var classname = ""
    @State private var campus = ""
    @State private var graduate = ""
    @State private var classunit = 0
    var body: some View {
        NavigationView {
            Text(university)
                .navigationBarItems(trailing: registrationButton)
        }
    }
    
    func registrationclass() {
        var products = [String: [String: Any]]()
        
        products["新入生セミナーB"] = ["name":"前原, 大塚","graduate":"共通教育","timetables":"火5,金5","timetable1":"火5","timetable2":"金5"]
        products["スポーツ"] = ["name":"井門, 上田","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["スポーツ"] = ["name":"市河, 上田","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["スポーツ"] = ["name":"林, 上田","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["スポーツ"] = ["name":"酒井, 上田","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["スポーツ"] = ["name":"西野, 上田","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["スポーツ"] = ["name":"丸山, 山本","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["スポーツ"] = ["name":"西野, 上田","graduate":"共通教育","timetables":"金3","timetable1":"金3","timetable2":""]
        products["スポーツ"] = ["name":"山中, 上田","graduate":"共通教育","timetables":"金3","timetable1":"金3","timetable2":""]
        products["スポーツ"] = ["name":"上田　敏子","graduate":"共通教育","timetables":"金3","timetable1":"金3","timetable2":""]
        products["総合英語A"] = ["name":"中山　晃","graduate":"共通教育","timetables":"水5","timetable1":"水5","timetable2":""]
        products["総合英語A"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"火6","timetable1":"火6","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"金城, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"尾國, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"檀, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"松澤, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"平田, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"三上, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"庭崎　隆","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"白柳, 庭崎","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["線形代数Ⅱ"] = ["name":"小林　千悟, 他","graduate":"共通教育","timetables":"火1","timetable1":"火1","timetable2":""]
        products["微積分Ⅱ"] = ["name":"井上　友喜","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"小西, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"松澤, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"三上, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"觀音, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"森岡, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"柳, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"畑田, 井上","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["微積分Ⅱ"] = ["name":"高井　和幸, 他","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["基礎微積分Ⅱ"] = ["name":"高井　和幸, 他","graduate":"共通教育","timetables":"金2","timetable1":"金2","timetable2":""]
        products["文系主題科目（知の探訪）【メディア授業科目】"] = ["name":"金西, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（モラエスの徳島）【メディア授業科目】"] = ["name":"金西, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（日本におけるドイツ兵捕虜1914-1920）【メディア授業科目】"] = ["name":"井戸, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（大学の知の活用）【メディア授業科目】"] = ["name":"井内, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（大学教育を考える）【メディア授業科目】"] = ["name":"吉田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（行動統計学入門）【メディア授業科目】"] = ["name":"山本, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（子どもと学校）【メディア授業科目】"] = ["name":"竹口幸志, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（学びの統合入門）【メディア授業科目】"] = ["name":"杉田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（NPOと大学の経営）【メディア授業科目】"] = ["name":"岩崎, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（ピア・サポート理論と実践）【メディア授業科目】"] = ["name":"杉田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（情報のいろは）【メディア授業科目】"] = ["name":"林 敏浩, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（現代科学と研究倫理）【メディア授業科目】"] = ["name":"金西, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（数理科学の世界）【メディア授業科目】"] = ["name":"大渕, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（情報社会のくらし）【メディア授業科目】"] = ["name":"竹口幸志, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（タンパク質で生命を斬る）【メディア授業科目】"] = ["name":"澤崎　達也, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（大学生のための『安全・安心』の基礎講座）【メディア授業科目】"] = ["name":"伊藤, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（留学生と日本人学生が共に学ぶ日本企業理解）"] = ["name":"泉谷　道子","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（留学生と日本人学生が共に学ぶ組織開発理論とその実践）"] = ["name":"泉谷　道子","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（現代日本の少子化問題について考える）"] = ["name":"長井　偉訓","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（英語で学ぶコントラクトブリッジ）"] = ["name":"ティモシー ブラッドフォード カーティス","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（ヒトはなぜ働くのか）"] = ["name":"阿部　光伸","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（外化を促すファシリテーション実践学【ピア・エデュケーション実践】）"] = ["name":"阿部　光伸","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["スポーツと教育"] = ["name":"石井　浩一, 他","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["スポーツと教育"] = ["name":"牛山　眞貴子, 他","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["スポーツと教育"] = ["name":"田中　雅人, 他","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["スポーツと教育"] = ["name":"石井　浩一, 他","graduate":"共通教育","timetables":"火3","timetable1":"火3","timetable2":""]
        products["スポーツと教育"] = ["name":"日野　克博, 他","graduate":"共通教育","timetables":"火3","timetable1":"火3","timetable2":""]
        products["スポーツと教育"] = ["name":"上田　敏子, 他","graduate":"共通教育","timetables":"火3","timetable1":"火3","timetable2":""]
        products["スポーツと教育"] = ["name":"福田　隆, 他","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["スポーツと教育"] = ["name":"糸岡　夕里, 他","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["スポーツと教育"] = ["name":"田中　雅人, 他","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["教職日本国憲法"] = ["name":"中曽　久雄","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["教職日本国憲法"] = ["name":"光信　一宏","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["教職日本国憲法"] = ["name":"井口　秀作","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["ベーシック海外サービスラーニング"] = ["name":"島上　宗子, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["アドバンスド海外サービスラーニング"] = ["name":"島上　宗子, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["環境ESD指導者養成講座Ⅰ"] = ["name":"小林　修, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["環境ESD指導者養成演習Ⅰ"] = ["name":"小林　修","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["環境ESD指導者養成演習Ⅱ"] = ["name":"小林　修","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["ファシリテーションとリーダーシップ"] = ["name":"仲道, 村田","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["グローバル・リーダーシップⅡ"] = ["name":"村田, 仲道","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["Speaking & Reading Strategies"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"水5","timetable1":"水5","timetable2":""]
        products["Effective Presentations"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["Writing Workshop"] = ["name":"中山　晃","graduate":"共通教育","timetables":"金5","timetable1":"金5","timetable2":""]
        products["Oral Communication"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["Discussion Skills"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"火5","timetable1":"火5","timetable2":""]
        products["Business English"] = ["name":"ｻﾊｲ ｵｸﾞﾊﾞﾏｲｹﾙ","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["English For Academic Research"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"金5","timetable1":"金5","timetable2":""]
        products["Oral Performance"] = ["name":"折本　素","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["Studying English Abroad Ⅱ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["英語S3"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"火5","timetable1":"火5","timetable2":""]
        products["英語S3"] = ["name":"ｻﾊｲ ｵｸﾞﾊﾞﾏｲｹﾙ","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["英語S3"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"金5","timetable1":"金5","timetable2":""]
        products["英語S3"] = ["name":"折本　素","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["英語S2"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["留学生と日本人学生が共に学ぶ日本企業理解"] = ["name":"泉谷　道子","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["留学生と日本人学生が共に学ぶ組織開発理論とその実践"] = ["name":"泉谷　道子","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["日本事情Ａ２"] = ["name":"ヒデイング　アドリアナ","graduate":"共通教育","timetables":"木3","timetable1":"木3","timetable2":""]
        products["日本事情Ｂ２"] = ["name":"村上　和弘","graduate":"共通教育","timetables":"火6","timetable1":"火6","timetable2":""]
        products["新入生セミナーB"] = ["name":"淡野　寧彦, 他","graduate":"共通教育","timetables":"月3,木3","timetable1":"月3","timetable2":"木3"]
        products["英語Ⅲ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"越智 美江","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅲ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"山本 淳子","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"折本　素","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅲ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅲ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅲ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅲ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅲ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅲ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"月1,木4","timetable1":"月1","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"月1,木4","timetable1":"月1","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅲ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅲ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅲ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅲ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅲ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅲ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅲ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅲ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅲ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅲ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅲ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["愛媛学"] = ["name":"村田　晋也","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["愛媛学"] = ["name":"阿部　光伸","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["日本語リテラシー入門"] = ["name":"秋山　英治","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["日本語リテラシー入門"] = ["name":"秋山　英治","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["知的財産入門"] = ["name":"宇戸　寿幸","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["知的財産入門"] = ["name":"岩本　幸治","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["知的財産入門"] = ["name":"木下　尚樹","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["知的財産入門"] = ["name":"朝日　剛","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["知的財産入門"] = ["name":"松本　圭介","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["知的財産入門"] = ["name":"神野　雅文","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["知的財産入門"] = ["name":"中曽　久雄","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["知的財産入門"] = ["name":"佐藤　智秋","graduate":"共通教育","timetables":"月6","timetable1":"月6","timetable2":""]
        products["知的財産入門"] = ["name":"中川　勝吾","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["知的財産入門"] = ["name":"有馬　誠一","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["知的財産入門"] = ["name":"高橋　学","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["知的財産入門"] = ["name":"高瀬　雅祥","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["知的財産入門"] = ["name":"小林, 加藤","graduate":"共通教育","timetables":"金4","timetable1":"金4","timetable2":""]
        products["科学技術リテラシー入門"] = ["name":"庭崎　隆","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["環境を考える"] = ["name":"田中　進","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"水川　葉月","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"松枝　直人","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"竹内　一郎","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["環境を考える"] = ["name":"吉冨　博之","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["倫理と思想を考える"] = ["name":"太田　裕信","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["倫理と思想を考える"] = ["name":"仲道　雅輝","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"畑守 泰子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"齊藤　貴弘","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"槙林　啓介","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["歴史を考える"] = ["name":"笹田　朋孝","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"西　耕生","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["ことばの世界"] = ["name":"上場 ゆり","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["ことばの世界"] = ["name":"太田　亨","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"井上　彰","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"小川　勉","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"青木　亮人","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"秋山　敏行","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["芸術の世界"] = ["name":"福富　彩子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["芸術の世界"] = ["name":"福井　一真","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"原田　義明","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"越智　雄磨","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"ネトラ　プラカシュ　バンダリィ","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"不破　茂","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"松村　暢彦","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"勝田　順一","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"松野尾　裕","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["現代社会の諸問題"] = ["name":"村田　晋也","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"中井　俊樹","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"中野　広輔","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"権　奇法","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"加藤　祐子","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"山口　和子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"門脇　一則","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"岡村, 吉井","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"大橋　淳史","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"秋山　浩一","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代と科学技術"] = ["name":"保田　和則","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["現代と科学技術"] = ["name":"樋上　喜信","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["自然のしくみ"] = ["name":"鍛冶澤　賢","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["自然のしくみ"] = ["name":"飯塚　剛","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["自然のしくみ"] = ["name":"羽生　剛","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["生命の不思議"] = ["name":"岸田　太郎","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"藤野　貴広","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"荒木　卓哉","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"佐久間　洋","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["生命の不思議"] = ["name":"古賀　理和","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["環境学入門"] = ["name":"山浦　弘之","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["人間科学入門"] = ["name":"羽鳥　剛史","graduate":"共通教育","timetables":"火7","timetable1":"火7","timetable2":""]
        products["人間科学入門（ことばの世界）"] = ["name":"上場 ゆり","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["人間科学入門"] = ["name":"竹中　喜一","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["生活科学入門"] = ["name":"古賀　理和","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["生活科学入門"] = ["name":"玉井　輝之","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["生活科学入門"] = ["name":"丸山　広達","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["哲学入門"] = ["name":"山本　與志隆","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["文学入門"] = ["name":"中根　隆行","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["言語学入門"] = ["name":"秋山　正宏","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["言語学入門"] = ["name":"佐藤　栄作","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["歴史学入門"] = ["name":"川岡　勉","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["考古学入門"] = ["name":"吉田　広","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["地理学入門"] = ["name":"寺谷　亮司","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["法学入門"] = ["name":"松原　英世","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["法学入門"] = ["name":"鈴木　靜","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["法学入門"] = ["name":"笹沼　朋子","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["経済学入門"] = ["name":"中西　泰造","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["経済学入門"] = ["name":"尾花　忠夫","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["経済学入門"] = ["name":"橘　惠昭","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["数学入門"] = ["name":"平野, 高橋","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["数学入門"] = ["name":"平野, 原本","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["物理学入門"] = ["name":"水上　孝一","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["物理学入門"] = ["name":"斎藤　全","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["物理学入門"] = ["name":"松下　正史","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["物理学入門"] = ["name":"山室　佐益","graduate":"共通教育","timetables":"土1","timetable1":"土1","timetable2":""]
        products["化学入門"] = ["name":"西脇　寿","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["化学入門"] = ["name":"御崎　洋二","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["生物学入門"] = ["name":"佐藤　康","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["生物学入門"] = ["name":"武森　信曉","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["工学入門"] = ["name":"川崎　健二","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["農学入門"] = ["name":"高橋　真, 他","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["初級ドイツ語Ⅲ"] = ["name":"寺下　太郎","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級ドイツ語Ⅲ"] = ["name":"寺下　太郎","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級ドイツ語Ⅲ"] = ["name":"野上, 伊藤","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級ドイツ語Ⅲ"] = ["name":"伊藤, 野上","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級フランス語Ⅲ"] = ["name":"越智, モヴェ・エリック","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級フランス語Ⅲ"] = ["name":"モヴェ・エリック, 越智","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級フランス語Ⅲ"] = ["name":"モヴェ・エリック, 田和","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級フランス語Ⅲ"] = ["name":"田和, モヴェ・エリック","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"秋谷, 陳","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"陳, 秋谷","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"陳, 秋谷","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"秋谷, 陳","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"宮田, 蒋","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級中国語Ⅲ"] = ["name":"蒋, 宮田","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"金, 張","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"張, 金","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"張, 金","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"金, 張","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"崔 昌玉","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級朝鮮語Ⅲ"] = ["name":"崔 昌玉","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級フィリピノ語Ⅲ"] = ["name":"菅谷　成子","graduate":"共通教育","timetables":"火5","timetable1":"火5","timetable2":""]
        products["初級フィリピノ語Ⅲ"] = ["name":"菅谷　成子","graduate":"共通教育","timetables":"金5","timetable1":"金5","timetable2":""]
        products["文系主題科目（地域コンテンツと知財管理　その１）【メディア授業科目】"] = ["name":"林 敏浩, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（香川を学ぶ　その１）【メディア授業科目】"] = ["name":"藤本憲市, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（四国の地域振興　その１）【メディア授業科目】"] = ["name":"林 敏浩, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（徳島を考える）【メディア授業科目】"] = ["name":"豊田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（キャリアで活かすITリテラシー）【メディア授業科目】"] = ["name":"高畑, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（業務効率化のためのIT活用入門）【メディア授業科目】"] = ["name":"高畑, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（キャリアプランニング）【メディア授業科目】"] = ["name":"森田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（消費生活入門）【メディア授業科目】"] = ["name":"小島, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（ユーラシア大陸における人と金属生産の関わり）【メディア授業科目】"] = ["name":"村上, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（アカデミック・プレゼンテーション（PowerPoint編））【メディア授業科目】"] = ["name":"仲道, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（インドネシアの文化と会話）【メディア授業科目】"] = ["name":"島上, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（研究倫理）【メディア授業科目】"] = ["name":"裏　和宏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（四国の自然環境と防災　その１）【メディア授業科目】"] = ["name":"寺尾 徹, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（高度情報化社会の歩き方）【メディア授業科目】"] = ["name":"後藤田 中, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（データ利活用とオープンイノベーションで創る未来のまちづくり）【メディア授業科目】"] = ["name":"米谷, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（インタフェースデザイン概論）【メディア授業科目】"] = ["name":"三好康夫, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（太陽光利用型植物工場における知能的農作物生産）【メディア授業科目】"] = ["name":"藤内　直道, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（昆虫と環境）【メディア授業科目】"] = ["name":"小西, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（私たちの生活と材料）【メディア授業科目】"] = ["name":"小林, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（身の回りの放射線）【メディア授業科目】"] = ["name":"岡野　聡, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（和算の世界）【メディア授業科目】"] = ["name":"河村, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（データサイエンスを活用した防災・危機管理）【メディア授業科目】"] = ["name":"野々村, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（レジリエントな社会の構築とコンピューターシミュレーション）【メディア授業科目】"] = ["name":"吉田, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（災害とデータサイエンス）【メディア授業科目】"] = ["name":"石塚, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（協同組合とは何か－協同組合論）"] = ["name":"西脇　秀一郎","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（新聞から学ぶ情報収集・伝達の方法）"] = ["name":"丸山　智子","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（地域企業の再発見）"] = ["name":"赤間　道夫","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（香りの科学）"] = ["name":"伊藤　和貴","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["アカデミックジャパニーズ３"] = ["name":"村上　和弘","graduate":"共通教育","timetables":"木5~6","timetable1":"木5~6","timetable2":""]
        products["英語Ⅳ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"高久保 文恵","graduate":"共通教育","timetables":"月2,木1","timetable1":"月2","timetable2":"木1"]
        products["英語Ⅳ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"山本 淳子","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火3,金2","timetable1":"火3","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"木下　英文","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火3,金3","timetable1":"火3","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火1,金2","timetable1":"火1","timetable2":"金2"]
        products["英語Ⅳ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"長崎　睦子","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"月3,木2","timetable1":"月3","timetable2":"木2"]
        products["英語Ⅳ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅳ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅳ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅳ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"月1,木3","timetable1":"月1","timetable2":"木3"]
        products["英語Ⅳ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"月1,木4","timetable1":"月1","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"月1,木4","timetable1":"月1","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"トレーシー　フリードリック","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"折本　素","graduate":"共通教育","timetables":"火2,金1","timetable1":"火2","timetable2":"金1"]
        products["英語Ⅳ"] = ["name":"トム　デジ　フェイミン","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"マーク・ドゥエイン・スタフォード","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"火2,金3","timetable1":"火2","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"火4,金3","timetable1":"火4","timetable2":"金3"]
        products["英語Ⅳ"] = ["name":"ジュリア カワモト　","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"中山　晃","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"火4,金4","timetable1":"火4","timetable2":"金4"]
        products["英語Ⅳ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"マーフィー・ロナルド・ポール","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"月2,木4","timetable1":"月2","timetable2":"木4"]
        products["英語Ⅳ"] = ["name":"今泉　志奈子","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅳ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅳ"] = ["name":"ジェーン　ワタナベ","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["英語Ⅳ"] = ["name":"アンドリユー　ストレンジ","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"イアン　ダウナー","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"レスリー　ブラック","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"ジョセフ　ナットレス","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"シンシア　ゴンザレズ","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"三浦　優生","graduate":"共通教育","timetables":"月5,木5","timetable1":"月5","timetable2":"木5"]
        products["英語Ⅳ"] = ["name":"クリスティン　アーミテージ","graduate":"共通教育","timetables":"火6,木6","timetable1":"火6","timetable2":"木6"]
        products["愛媛学"] = ["name":"村田　晋也","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["愛媛学"] = ["name":"秋丸　國廣","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["社会力入門"] = ["name":"野本　ひさ, 他","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["社会力入門"] = ["name":"阿部　光伸, 他","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["社会力入門"] = ["name":"丸山　智子, 他","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["社会力入門"] = ["name":"野本　ひさ, 他","graduate":"共通教育","timetables":"月3","timetable1":"月3","timetable2":""]
        products["社会力入門"] = ["name":"阿部　光伸, 他","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["社会力入門"] = ["name":"丸山　智子, 他","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["社会力入門"] = ["name":"野本　ひさ, 他","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["社会力入門"] = ["name":"丸山　智子, 他","graduate":"共通教育","timetables":"水3","timetable1":"水3","timetable2":""]
        products["社会力入門"] = ["name":"阿部　光伸, 他","graduate":"共通教育","timetables":"月6","timetable1":"月6","timetable2":""]
        products["環境を考える"] = ["name":"田中　進","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"水川　葉月","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"松枝　直人","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["環境を考える"] = ["name":"竹内　一郎","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["環境を考える"] = ["name":"吉冨　博之","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["倫理と思想を考える"] = ["name":"太田　裕信","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["倫理と思想を考える"] = ["name":"仲道　雅輝","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"畑守 泰子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"齊藤　貴弘","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["歴史を考える"] = ["name":"槙林　啓介","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["歴史を考える"] = ["name":"笹田　朋孝","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"西　耕生","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["ことばの世界"] = ["name":"上場 ゆり","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["ことばの世界"] = ["name":"太田　亨","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"井上　彰","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"小川　勉","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["ことばの世界"] = ["name":"青木　亮人","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"秋山　敏行","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["芸術の世界"] = ["name":"福富　彩子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["芸術の世界"] = ["name":"福井　一真","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"原田　義明","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["芸術の世界"] = ["name":"越智　雄磨","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"ネトラ　プラカシュ　バンダリィ","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"不破　茂","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"松村　暢彦","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"勝田　順一","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["社会のしくみを考える"] = ["name":"松野尾　裕","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["現代社会の諸問題"] = ["name":"村田　晋也","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"中井　俊樹","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"中野　広輔","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"権　奇法","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"加藤　祐子","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代社会の諸問題"] = ["name":"山口　和子","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"門脇　一則","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"岡村, 吉井","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"大橋　淳史","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["現代と科学技術"] = ["name":"秋山　浩一","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["現代と科学技術"] = ["name":"保田　和則","graduate":"共通教育","timetables":"木7","timetable1":"木7","timetable2":""]
        products["現代と科学技術"] = ["name":"樋上　喜信","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["自然のしくみ"] = ["name":"鍛冶澤　賢","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["自然のしくみ"] = ["name":"飯塚　剛","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["自然のしくみ"] = ["name":"羽生　剛","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["生命の不思議"] = ["name":"岸田　太郎","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"藤野　貴広","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"荒木　卓哉","graduate":"共通教育","timetables":"月2","timetable1":"月2","timetable2":""]
        products["生命の不思議"] = ["name":"佐久間　洋","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["生命の不思議"] = ["name":"古賀　理和","graduate":"共通教育","timetables":"木2","timetable1":"木2","timetable2":""]
        products["環境学入門"] = ["name":"山浦　弘之","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["人間科学入門"] = ["name":"竹中　喜一","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["生活科学入門"] = ["name":"古賀　理和","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["生活科学入門"] = ["name":"玉井　輝之","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["生活科学入門"] = ["name":"丸山　広達","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["哲学入門"] = ["name":"山本　與志隆","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["文学入門"] = ["name":"中根　隆行","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["文学入門"] = ["name":"柳　光子","graduate":"共通教育","timetables":"火7","timetable1":"火7","timetable2":""]
        products["言語学入門"] = ["name":"秋山　正宏","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["言語学入門"] = ["name":"佐藤　栄作","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["言語学入門（ことばの世界）"] = ["name":"上場 ゆり","graduate":"共通教育","timetables":"水2","timetable1":"水2","timetable2":""]
        products["歴史学入門"] = ["name":"川岡　勉","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["考古学入門"] = ["name":"吉田　広","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["地理学入門"] = ["name":"寺谷　亮司","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["法学入門"] = ["name":"松原　英世","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["法学入門"] = ["name":"鈴木　靜","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["法学入門"] = ["name":"笹沼　朋子","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["経済学入門"] = ["name":"中西　泰造","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["経済学入門"] = ["name":"尾花　忠夫","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["経済学入門"] = ["name":"橘　惠昭","graduate":"共通教育","timetables":"月4","timetable1":"月4","timetable2":""]
        products["心理学入門"] = ["name":"加藤　匡宏","graduate":"共通教育","timetables":"土1","timetable1":"土1","timetable2":""]
        products["数学入門"] = ["name":"平野, 高橋","graduate":"共通教育","timetables":"木1","timetable1":"木1","timetable2":""]
        products["数学入門"] = ["name":"平野, 新関","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["物理学入門"] = ["name":"水上　孝一","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["物理学入門"] = ["name":"斎藤　全","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["物理学入門"] = ["name":"松下　正史","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["化学入門"] = ["name":"西脇　寿","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["化学入門"] = ["name":"御崎　洋二","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["生物学入門"] = ["name":"佐藤　康","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["生物学入門"] = ["name":"武森　信曉","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["工学入門"] = ["name":"川崎　健二","graduate":"共通教育","timetables":"火2","timetable1":"火2","timetable2":""]
        products["農学入門"] = ["name":"高橋　真, 他","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["数学入門"] = ["name":"松浦　真也, 他","graduate":"共通教育","timetables":"月1","timetable1":"月1","timetable2":""]
        products["初級ドイツ語Ⅳ"] = ["name":"寺下　太郎","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級ドイツ語Ⅳ"] = ["name":"寺下　太郎","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級ドイツ語Ⅳ"] = ["name":"野上, 伊藤","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級ドイツ語Ⅳ"] = ["name":"伊藤, 野上","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級フランス語Ⅳ"] = ["name":"越智, モヴェ・エリック","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級フランス語Ⅳ"] = ["name":"モヴェ・エリック, 越智","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級フランス語Ⅳ"] = ["name":"モヴェ・エリック, 田和","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級フランス語Ⅳ"] = ["name":"田和, モヴェ・エリック","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"秋谷, 陳","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"陳, 秋谷","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"陳, 秋谷","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"秋谷, 陳","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"宮田, 蒋","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級中国語Ⅳ"] = ["name":"蒋, 宮田","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"金, 張","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"張, 金","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"張, 金","graduate":"共通教育","timetables":"月5","timetable1":"月5","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"金, 張","graduate":"共通教育","timetables":"木5","timetable1":"木5","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"崔 昌玉","graduate":"共通教育","timetables":"水6","timetable1":"水6","timetable2":""]
        products["初級朝鮮語Ⅳ"] = ["name":"崔 昌玉","graduate":"共通教育","timetables":"金6","timetable1":"金6","timetable2":""]
        products["初級フィリピノ語Ⅳ"] = ["name":"菅谷　成子","graduate":"共通教育","timetables":"火5","timetable1":"火5","timetable2":""]
        products["初級フィリピノ語Ⅳ"] = ["name":"菅谷　成子","graduate":"共通教育","timetables":"金5","timetable1":"金5","timetable2":""]
        products["文系主題科目（地域コンテンツと知財管理　その２）【メディア授業科目】"] = ["name":"林 敏浩, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（香川を学ぶ　その２）【メディア授業科目】"] = ["name":"藤本憲市, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["文系主題科目（四国の地域振興　その２）【メディア授業科目】"] = ["name":"林 敏浩, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（四国の自然環境と防災　その２）【メディア授業科目】"] = ["name":"寺尾 徹, 他","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["理系主題科目（自動車概論）【メディア授業科目】"] = ["name":"宮下晃一, 裏","graduate":"共通教育","timetables":"集中","timetable1":"集中","timetable2":""]
        products["アカデミックジャパニーズ４"] = ["name":"高橋　志野","graduate":"共通教育","timetables":"月6,水6","timetable1":"月6","timetable2":"水6"]
        
        
        
        for (key, value) in products {
            print("product name: ", key)
            let courseName = key
            value.forEach {
                if String($0.key) == "name" {
                    teacherName = $0.value as! String
                } else if String($0.key) == "code" {
                    classcode = $0.value as! String
                } else if String($0.key) == "unit" {
                    classunit = $0.value as! Int
                } else if String($0.key) == "timetables" {
                    timetables = $0.value as! String
                } else if String($0.key) == "campus" {
                    campus = $0.value as! String
                } else if String($0.key) == "graduate" {
                    graduate = $0.value as! String
                } else if String($0.key) == "classname" {
                    classname = $0.value as! String
                } else if String($0.key) == "timetable1" {
                    timetable1 = $0.value as! String
                } else if String($0.key) == "timetable2" {
                    timetable2 = $0.value as! String
                }
            }
            
            let docfef = COLLECTION_TIMETABLE.document(university).collection("2021AS").document()
            let docID = docfef.documentID
            //            let Docfef = COLLECTION_TIMETABLE.document(university).collection("\(campus)").document("2021AS").collection("\(timetables)").document(docID)
            
            
            let datas: [String: Any] = ["university": university,
                                        "campus": campus,
                                        "courseName": courseName,
                                        "roomLocation": "",
                                        "teacherName": teacherName,
                                        "unit": classunit,
                                        "author": "",
                                        "classCode": classcode,
                                        "graduate": graduate,
                                        "timetables": timetables,
                                        "timetable": [timetable1,timetable2],
                                        "classname": classname,
                                        "reference_source": "\(university) / シラバス",
                                        "classId": docID]
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                //                Docfef.setData(datas) { _ in
                //                }
                docfef.setData(datas) { _ in
                }
            }
        }
    }
    var registrationButton: some View {
        Button(action: {
            registrationclass()
        }, label: {
            Text("作成")
                .bold()
                .font(Font.system(size: 17, weight: .bold))
                .foregroundColor(courseName != "" ? Color(red: 104/255, green: 171/255, blue: 121/255) : Color.gray.opacity(0.7))
        })
    }
}
