//
//  KansaiUniversity.swift
//  KansaiUniversity
//
//  Created by 髙間洋平 on 2021/08/21.
//

import SwiftUI

enum KansaiUniversity: String, CaseIterable {
    case aino // 藍野大学
    case asiya // 芦屋大学
    case osaka // 大阪大学
    case ooasakaaoyama // 大阪青山大学
    case oosakaikayakka // 大阪医科薬科大学
    case osakaotani // 大阪大谷大学
    case oosakaonngaku // 大阪音楽大学
    case oosakagakuinn // 大阪学院大学
    case oosakakawasakirihabiritesyonn // 大阪川崎リハビリテーション大学
    case oosakakannkou // 大阪観光大学
    case osakakyoiku // 大阪教育大学
    case osakakeizai // 大阪経済大学
    case osakakeizaihoka // 大阪経済法科大学
    case oosakageijutu // 大阪芸術大学
    case osakakogyou // 大阪工業大学
    case osakakoritu // 大阪公立大学
    case osakakokusai // 大阪国際大学
    case osakasaigyou // 大阪産業大学
    case oosakasika // 大阪歯科大学
    case osakasyoinjyoshi // 大阪樟蔭女子大学
    case oosakajogakuinn // 大阪女学院大学
    case osakasyogyou // 大阪商業大学
    case oosakasinaigakuinn // 大阪信愛学院大学
    case oosakaseikei // 大阪成蹊大学
    case osakasogohoiku // 大阪総合保育大学
    case osakataiku // 大阪体育大学
    case oosakadennkituusinn // 大阪電気通信大学
    case oosakaninngennkagaku // 大阪人間科学大学
    case oosakabuturyou // 大阪物療大学
    case oosakahokenniryou // 大阪保健医療大学
    case oosakayukiokairyou // 大阪行岡医療大学
    case ootani // 大谷大学
    case otemae // 大手前大学
    case otemongakuin // 追手門学院大学
    case Kansai // 関西大学
    case kannsaiika // 関西医科大学
    case kannsaiiryou // 関西医療大学
    case kansaigaikokugo // 関西外国語大学
    case Kansaigakuin // 関西学院大学
    case kannsaikanngoiryou // 関西看護医療大学
    case kansaikokusai // 関西国際大学
    case kansaihukushi // 関西福祉大学
    case kannsaihukusikagaku // 関西福祉科学大学
    case kiou // 畿央大学
    case kyoto // 京都大学
    case kyotoitiritugeijyutu // 京都市立芸術大学
    case kyotoiryoukagaku // 京都医療科学大学
    case kyotogaikokugo // 京都外国語大学
    case kyoutokatyou // 京都華頂大学
    case kyoutokanngo // 京都看護大学
    case kyotokyoiku // 京都教育大学
    case kyotogeijyutu // 京都芸術大学
    case kyotogeijyutukougei // 京都芸術工芸大学
    case kyotokokajyoshi // 京都光華女子大学
    case kyotokogeiseni // 京都工芸繊維大学
    case Kyotosangyou // 京都産業大学
    case kyotojyoshi // 京都女子大学
    case kyotoseika // 京都精華大学
    case kyotosentankagaku // 京都先端科学大学
    case kyototatibana // 京都橘大学
    case kyotonotorudamjyoshi // 京都ノートルダム女子大学
    case kyoutobijutukougei // 京都美術工芸大学
    case kyotohuritu // 京都府立大学
    case kyotohurituika // 京都府立医科大学
    case kyotobunkyou // 京都文教大学
    case kyoutoyakka // 京都薬科大学
    case Kinki // 近畿大学
    case gejyutubunkakankousenmonsyoku // 芸術文化観光専門職大学
    case kougakkann // 皇学館大学
    case kosien // 甲子園大学
    case kounan // 甲南大学
    case konanjyoshi // 甲南女子大学
    case kobe // 神戸大学
    case koubeiryouhukusi // 神戸医療福祉大学
    case koubekaiseijosigakuinn // 神戸海星女子学院大学
    case kobegakuin // 神戸学院大学
    case koubegeijutukouka // 神戸芸術工科大学
    case kobeshikango // 神戸市看護大学
    case kobeshigaikoukugo // 神戸市外国語大学
    case koubekokusai // 神戸国際大学
    case kobesyoinjyoshigakuin // 神戸松蔭女子学院大学
    case koubejogakuinn // 神戸女学院大学
    case koubejyosi // 神戸女子大学
    case kobesinwajyoshi // 神戸親和女子大学
    case kobetokiwa // 神戸常盤大学
    case koubeyakka // 神戸薬科大学
    case sagabijutu // 嵯峨美術大学
    case shiga // 滋賀大学
    case shigaika // 滋賀医科大学
    case shigakenritu // 滋賀県立大学
    case jikeiiryoukagaku // 滋慶医療科学大学
    case sijounawategakuenn // 四条畷学園大学
    case sitennnouji // 四天王寺大学
    case syutiinn // 種智院大学
    case suzuka // 鈴鹿大学
    case suzukairyoukagaku // 鈴鹿医療科学大学
    case seiannzoukei // 成安造形大学
    case seisenn // 聖泉大学
    case setunen // 摂南大学
    case sennrikinnrann // 千里金蘭大学
    case souai // 相愛大学
    case sonodegakuinjyoshi // 園田学園女子大学
    case taiseigakuinn // 太成学院大学
    case kouyasann // 高野山大学
    case takaraduka // 宝塚大学
    case takaradukairyou // 宝塚医療大学
    case tezukayama // 帝塚山大学
    case tezukayamagakuinn // 帝塚山学院大学
    case tenri // 天理大学
    case tennriiryou // 天理医療大学
    case Dousisya // 同志社大学
    case Dousisyajosi // 同志社女子大学
    case tokiwakaigakuenn // 常磐会学園大学
    case nagahamabaio // 長浜バイオ大学
    case Nagoya // 名古屋大学
    case Nagoyakogyo // 名古屋工業大学
    case nara // 奈良大学
    case naragakuen // 奈良学園大学
    case narakyoiku // 奈良教育大学
    case narakenritu // 奈良県立大学
    case narakenrituika // 奈良県立医科大学
    case narajyoshi // 奈良女子大学
    case baikajyoshi // 梅花女子大学
    case hagoromokokusai // 羽衣国際大学
    case hanazono // 花園大学
    case hannan // 阪南大学
    case higasioosaka // 東大阪大学
    case himeji // 姫路大学
    case himejidokkyou // 姫路獨協大学
    case hyougo // 兵庫大学
    case hyougoika // 兵庫医科大学
    case hyogokyouiku // 兵庫教育大学
    case hyogokenritu // 兵庫県立大学
    case biwakogakuinn // びわこ学院大学
    case biwakoseikeisupotu // びわこ成蹊スポーツ大学
    case biwakorihabirisennmonsyoku // びわこリハビリ専門職大学
    case hukutiyamakouritu // 福知山公立大学
    case bukkyo // 佛教大学
    case heiannjogakuinn // 平安女学院大学
    case mie // 三重大学
    case miekennritukanngo // 三重県立看護大学
    case mukogawajyoshi // 武庫川女子大学
    case meijikokusaiiryou // 明治国際医療大学
    case momoyamagakuin // 桃山学院大学
    case momoyamagakuinkyoiku // 桃山学院教育大学
    case morinomiyairyou // 森ノ宮医療大学
    case yamato // 大和大学
    case yokkaiti // 四日市大学
    case yokkaitikanngoiryou // 四日市看護医療大学
    case Ritumeikan // 立命館大学
    case Ryukoku // 龍谷大学
    case ryutukagaku // 流通科学大学
    case wakayama // 和歌山大学
    case wakayamasinai // 和歌山信愛大学
    case wakayamakenrituika // 和歌山県立医科大学
    case wakayamarihabiritesyonsennmonnsyoku // 和歌山リハビリテーション専門職大学
    
    var name: String {
        switch self {
        case .asiya: return "芦屋大学"
        case .aino: return "藍野大学"
        case .ootani: return "大谷大学"
        case .osaka: return "大阪大学"
        case .ooasakaaoyama: return "大阪青山大学"
        case .oosakaikayakka: return "大阪医科薬科大学"
        case .osakaotani: return "大阪大谷大学"
        case .oosakaonngaku: return "大阪音楽大学"
        case .oosakagakuinn: return "大阪学院大学"
        case .oosakakawasakirihabiritesyonn: return "大阪川崎リハビリテーション大学"
        case .oosakakannkou: return "大阪観光大学"
        case .osakakyoiku: return "大阪教育大学"
        case .osakakeizai: return "大阪経済大学"
        case .osakakeizaihoka: return "大阪経済法科大学"
        case .oosakageijutu: return "大阪芸術大学"
        case .osakakoritu: return "大阪公立大学"
        case .osakakogyou: return "大阪工業大学"
        case .osakakokusai: return "大阪国際大学"
        case .osakasaigyou: return "大阪産業大学"
        case .oosakasika: return "大阪歯科大学"
        case .osakasyoinjyoshi: return "大阪樟蔭女子大学"
        case .osakasyogyou: return "大阪商業大学"
        case .oosakajogakuinn: return "大阪女学院大学"
        case .oosakasinaigakuinn: return "大阪信愛学院大学"
        case .oosakaseikei: return "大阪成蹊大学"
        case .osakasogohoiku: return "大阪総合保育大学"
        case .osakataiku: return "大阪体育大学"
        case .oosakadennkituusinn: return "大阪電気通信大学"
        case .oosakaninngennkagaku: return "大阪人間科学大学"
        case .oosakabuturyou: return "大阪物療大学"
        case .oosakahokenniryou: return "大阪保健医療大学"
        case .oosakayukiokairyou: return "大阪行岡医療大学"
        case .otemae: return "大手前大学"
        case .otemongakuin: return "追手門学院大学"
        case .Kansai: return "関西大学"
        case .kannsaiika: return "関西医科大学"
        case .kannsaiiryou: return "関西医療大学"
        case .kansaigaikokugo: return "関西外国語大学"
        case .Kansaigakuin: return "関西学院大学"
        case .kannsaikanngoiryou: return "関西看護医療大学"
        case .kansaikokusai: return "関西国際大学"
        case .kansaihukushi: return "関西福祉大学"
        case .kannsaihukusikagaku: return "関西福祉科学大学"
        case .kiou: return "畿央大学"
        case .kyoto: return "京都大学"
        case .kyotoitiritugeijyutu: return "京都市立芸術大学"
        case .kyotoiryoukagaku: return "京都医療科学大学"
        case .kyotogaikokugo: return "京都外国語大学"
        case .kyoutokatyou: return "京都華頂大学"
        case .kyoutokanngo: return "京都看護大学"
        case .kyotokyoiku: return "京都教育大学"
        case .kyotogeijyutu: return "京都芸術大学"
        case .kyotogeijyutukougei: return "京都芸術工芸大学"
        case .kyotokokajyoshi: return "京都光華女子大学"
        case .kyotokogeiseni: return "京都工芸繊維大学"
        case .Kyotosangyou: return "京都産業大学"
        case .kyotojyoshi: return "京都女子大学"
        case .kyotoseika: return "京都精華大学"
        case .kyotosentankagaku: return "京都先端科学大学"
        case .kyototatibana: return "京都橘大学"
        case .kyotonotorudamjyoshi: return "京都ノートルダム女子大学"
        case .kyoutobijutukougei: return "京都美術工芸大学"
        case .kyotohuritu: return "京都府立大学"
        case .kyotohurituika: return "京都府立医科大学"
        case .kyotobunkyou: return "京都文教大学"
        case .kyoutoyakka: return "京都薬科大学"
        case .Kinki: return "近畿大学"
        case .gejyutubunkakankousenmonsyoku: return "芸術文化観光専門職大学"
        case .kougakkann: return "皇学館大学"
        case .kosien: return "甲子園大学"
        case .kounan: return "甲南大学"
        case .konanjyoshi: return "甲南女子大学"
        case .kobe: return "神戸大学"
        case .koubeiryouhukusi: return "神戸医療福祉大学"
        case .kobeshigaikoukugo: return "神戸市外国語大学"
        case .koubekaiseijosigakuinn: return "神戸海星女子学院大学"
        case .kobegakuin: return "神戸学院大学"
        case .koubegeijutukouka: return "神戸芸術工科大学"
        case .koubekokusai: return "神戸国際大学"
        case .kobeshikango: return "神戸市看護大学"
        case .koubejyosi: return "神戸女子大学"
        case .kobesyoinjyoshigakuin: return "神戸松蔭女子学院大学"
        case .koubejogakuinn: return "神戸女学院大学"
        case .kobesinwajyoshi: return "神戸親和女子大学"
        case .kobetokiwa: return "神戸常盤大学"
        case .koubeyakka: return "神戸薬科大学"
        case .kouyasann: return "高野山大学"
        case .sagabijutu: return "嵯峨美術大学"
        case .shiga: return "滋賀大学"
        case .shigaika: return "滋賀医科大学"
        case .shigakenritu: return "滋賀県立大学"
        case .jikeiiryoukagaku: return "滋慶医療科学大学"
        case .sijounawategakuenn: return "四条畷学園大学"
        case .sitennnouji: return "四天王寺大学"
        case .syutiinn: return "種智院大学"
        case .seiannzoukei: return "成安造形大学"
        case .seisenn: return "聖泉大学"
        case .setunen: return "摂南大学"
        case .sennrikinnrann: return "千里金蘭大学"
        case .suzuka: return "鈴鹿大学"
        case .suzukairyoukagaku: return "鈴鹿医療科学大学"
        case .souai: return "相愛大学"
        case .sonodegakuinjyoshi: return "園田学院女子大学"
        case .taiseigakuinn: return "太成学院大学"
        case .takaraduka: return "宝塚大学"
        case .takaradukairyou: return "宝塚医療大学"
        case .tezukayama: return "帝塚山大学"
        case .tezukayamagakuinn: return "手塚山学院大学"
        case .tenri: return "天理大学"
        case .tennriiryou: return "天理医療大学"
        case .Dousisya: return "同志社大学"
        case .Dousisyajosi: return "同志社女子大学"
        case .tokiwakaigakuenn: return "常磐会学園大学"
        case .nagahamabaio: return "長浜バイオ大学"
        case .Nagoya: return "名古屋大学"
        case .Nagoyakogyo: return "名古屋工業大学"
        case .nara: return "奈良大学"
        case .naragakuen: return "奈良学園大学"
        case .narakenritu: return "奈良県立大学"
        case .narakyoiku: return "奈良教育大学"
        case .narakenrituika: return "奈良県立医科大学"
        case .narajyoshi: return "奈良女子大学"
        case .baikajyoshi: return "梅花女子大学"
        case .hagoromokokusai: return "羽衣国際大学"
        case .hanazono: return "花園大学"
        case .hannan: return "阪南大学"
        case .higasioosaka: return "東大阪大学"
        case .himeji: return "姫路大学"
        case .himejidokkyou: return "姫路獨協大学"
        case .hyougo: return "兵庫大学"
        case .hyougoika: return "兵庫医科大学"
        case .hyogokyouiku: return "兵庫教育大学"
        case .hyogokenritu: return "兵庫県立大学"
        case .biwakogakuinn: return "びわこ学院大学"
        case .biwakoseikeisupotu: return "びわこ成蹊スポーツ大学"
        case .biwakorihabirisennmonsyoku: return "びわこリハビリ専門職大学"
        case .hukutiyamakouritu: return "福知山公立大学"
        case .bukkyo: return "佛教大学"
        case .heiannjogakuinn: return "平安女学院大学"
        case .mie: return "三重大学"
        case .miekennritukanngo: return "三重県立看護大学"
        case .mukogawajyoshi: return "武庫川女子大学"
        case .meijikokusaiiryou: return "明治国際医療大学"
        case .momoyamagakuin: return "桃山学院大学"
        case .momoyamagakuinkyoiku: return "桃山学院教育大学"
        case .morinomiyairyou: return "森ノ宮医療大学"
        case .yamato: return "大和大学"
        case .yokkaiti: return "四日市大学"
        case .yokkaitikanngoiryou: return "四日市看護医療大学"
        case .Ritumeikan: return "立命館大学"
        case .Ryukoku: return "龍谷大学"
        case .ryutukagaku: return "流通科学大学"
        case .wakayama: return "和歌山大学"
        case .wakayamakenrituika: return "和歌山県立医科大学"
        case .wakayamasinai: return "和歌山信愛大学"
        case .wakayamarihabiritesyonsennmonnsyoku: return "和歌山リハビリ専門職大学"
        
            }
    }
    
    var description: [String] {
        switch self {
        case .aino: return ["--","本校"]
        case .asiya: return ["--","六麓荘キャンパス"]
        case .ootani: return ["--","本部キャンパス","湖西キャンパス"]
        case .osaka: return ["--","豊中キャンパス","吹田キャンパス","箕面キャンパス"]
        case .ooasakaaoyama: return ["--","箕面キャンパス","北摂キャンパス"]
        case .oosakaikayakka: return ["--","本部キャンパス","本部北キャンパス","本部北西キャンパス","城北キャンパス","さわらぎキャンパス"]
        case .osakaotani: return ["--","本校"]
        case .oosakaonngaku: return ["--","本校"]
        case .oosakagakuinn: return ["--","本校"]
        case .oosakakawasakirihabiritesyonn: return ["--","本校"]
        case .oosakakannkou: return ["--","本校"]
        case .osakakyoiku: return ["--","天王寺キャンパス","柏原キャンパス"]
        case .osakakeizai: return ["--","大隅キャンパス","北浜キャンパス"]
        case .osakakeizaihoka: return ["--","花岡キャンパス","八尾駅前キャンパス"]
        case .oosakageijutu: return ["--","本学キャンパス","スカイキャンパス"]
        case .osakakogyou: return ["--","大宮キャンパス","梅田キャンパス","枚方キャンパス"]
        case .osakakoritu: return ["--","杉元キャンパス","阿倍野キャンパス","羽曳野キャンパス","中百舌鳥キャンパス","りんくうキャンパス","梅田サテライト"]
        case .osakakokusai: return ["--","本校"]
        case .osakasaigyou: return ["--","中央キャンパス","東キャンパス","南キャンパス","生駒キャンパス"]
        case .oosakasika: return ["--","葛葉キャンパス","牧野キャンパス","天満橋キャンパス"]
        case .osakasyogyou: return ["--","本校"]
        case .osakasyoinjyoshi: return ["--","本校"]
        case .oosakajogakuinn: return ["--","本校"]
        case .oosakasinaigakuinn: return ["--","城東キャンパス","鶴見キャンパス"]
        case .oosakaseikei: return ["--","本校"]
        case .osakasogohoiku: return ["--","本校"]
        case .osakataiku: return ["--","本校"]
        case .oosakadennkituusinn: return ["--","寝屋川キャンパス","四條畷キャンパス"]
        case .oosakaninngennkagaku: return ["--","本校"]
        case .oosakabuturyou: return ["--","1号館・2号館","3号館","4号館"]
        case .oosakahokenniryou: return ["--","1号館","2号館"]
        case .oosakayukiokairyou: return ["--","本校"]
        case .otemae: return ["--","さくら夙川キャンパス","大阪大手前キャンパス","本校"]
        case .otemongakuin: return ["--","茨木安威","茨木総持寺"]
        case .Kansai: return ["--","本校"]
        case .kannsaiika: return ["--","枚方キャンパス","牧野キャンパス"]
        case .kannsaiiryou: return ["--","本校"]
        case .kansaigaikokugo: return ["--","中宮キャンパス","御殿山キャンパス・グローバルタウン","片鉾キャンパス","学研都市キャンパス"]
        case .Kansaigakuin: return ["--","本校"]
        case .kannsaikanngoiryou: return ["--","本校"]
        case .kansaikokusai: return ["--","三木キャンパス","尾崎キャンパス","神戸山手キャンパス"]
        case .kansaihukushi: return ["--","本校"]
        case .kiou: return ["--","本校"]
        case .kyoto: return ["--","吉田キャンパス","宇治キャンパス","桂キャンパス"]
        case .kyotoiryoukagaku: return ["--","本校"]
        case .kyotogaikokugo: return ["--","本校"]
        case .kyoutokatyou: return ["--","本校"]
        case .kyoutokanngo: return ["--","本校"]
        case .kyotokyoiku: return ["--","本校"]
        case .kyotogeijyutu: return ["--","本校"]
        case .kyotogeijyutukougei: return ["--","本校"]
        case .kyotokogeiseni: return ["--","松ヶ崎キャンパス","福知山キャンパス"]
        case .kyotokokajyoshi: return ["--","本校"]
        case .Kyotosangyou: return ["--","本校"]
        case .kyotojyoshi: return ["--","本校"]
//        case .kyotoshiritugeijyutu: return ["--","本校"]
        case .kyotoseika: return ["--","本校"]
        case .kyotosentankagaku: return ["--","太秦キャンパス","亀岡キャンパス"]
        case .kyototatibana: return ["--","本校"]
        case .kyotonotorudamjyoshi: return ["--","本校"]
        case .kyotohuritu: return ["--","本校"]
        case .kyotohurituika: return ["--","広小路キャンパス","河原町キャンパス","下鴨キャンパス"]
        case .kyotobunkyou: return ["--","本校"]
        case .kyoutoyakka: return ["--","本校地","南校地"]
        case .Kinki: return ["--","東大阪","大阪狭山キャンパス","奈良キャンパス","和歌山キャンパス","広島キャンパス","福岡キャンパス"]
        case .gejyutubunkakankousenmonsyoku: return ["--","本校"]
        case .kougakkann: return ["--","本校"]
        case .kounan: return ["--","岡本キャンパス","西宮キャンパス","ポートアイランドキャンパス","白川台キャンパス"]
        case .konanjyoshi: return ["--","本校"]
        case .kosien: return ["--","本校"]
        case .kobe: return ["--","六甲台第1キャンパス","六甲台第2キャンパス","鶴甲第1キャンパス","鶴甲第2キャンパス"]
        case .koubeiryouhukusi: return ["--","姫路キャンパス","大阪天王寺キャンパス","神戸サテライトキャンパス"]
        case .koubekaiseijosigakuinn: return ["--","本校"]
        case .koubegeijutukouka: return ["--","本校"]
        case .kobegakuin: return ["--","ポートアイランドキャンパス","有瀬キャンパス"]
        case .koubekokusai: return ["--","本校"]
        case .kobeshikango: return ["--","本校"]
        case .kobeshigaikoukugo: return ["--","本校"]
        case .kobesyoinjyoshigakuin: return ["--","本校"]
        case .koubejogakuinn: return ["--","本校"]
        case .kobesinwajyoshi: return ["--","本校"]
        case .koubejyosi: return ["--","須磨キャンパス","ポートアイランドキャンパス","三宮キャンパス"]
        case .kobetokiwa: return ["--","本校"]
        case .koubeyakka: return ["--","本校"]
        case .kouyasann: return ["--","本校"]
        case .sagabijutu: return ["--","本部キャンパス","罧原キャンパス"]
        case .syutiinn: return ["--","本校"]
        case .shiga: return ["--","大津キャンパス","彦根キャンパス","本校"]
        case .shigaika: return ["--","本校"]
        case .shigakenritu: return ["--","本校"]
        case .jikeiiryoukagaku: return ["--","本校"]
        case .sijounawategakuenn: return ["--","北条キャンパス","学園町キャンパス"]
        case .sitennnouji: return ["--","本キャンパス","東キャンパス","あべのハルカスサテライトキャンパス"]
        case .sennrikinnrann: return ["--","本校"]
        case .souai: return ["--","本校"]
        case .suzuka: return ["--","本校"]
        case .suzukairyoukagaku: return ["--","千代崎キャンパス","白子キャンパス"]
        case .seiannzoukei: return ["--","本校"]
        case .seisenn: return ["--","本校"]
        case .setunen: return ["--","寝屋川キャンパス","枚方キャンパス"]
        case .sonodegakuinjyoshi: return ["--","本校"]
        case .taiseigakuinn: return ["--","本校"]
        case .takaraduka: return ["--","大阪梅田キャンパス","東京新宿キャンパス"]
        case .takaradukairyou: return ["--","本校"]
        case .tezukayamagakuinn: return ["--","本校"]
        case .tezukayama: return ["--","東生駒キャンパス","学園前キャンパス"]
        case .tenri: return ["--","杣之内キャンパス","体育学部キャンパス"]
        case .tennriiryou: return ["--","本校"]
        case .Dousisya: return ["--","今出川キャンパス","新町キャンパス","室町キャンパス","京田辺キャンパス","大阪サテライトキャンパス","東京サテライトキャンパス"]
        case .Dousisyajosi: return ["--","今出川キャンパス","京田辺キャンパス"]
        case .tokiwakaigakuenn: return ["--","本校"]
        case .nagahamabaio: return ["--","本校"]
        case .Nagoya: return ["--","東山キャンパス","鶴舞キャンパス","大幸キャンパス"]
        case .Nagoyakogyo: return ["--","御器所キャンパス","本校"]
        case .nara: return ["--","本校"]
        case .naragakuen: return ["--","三郷キャンパス","登美ヶ丘キャンパス"]
        case .narakyoiku: return ["--","本校"]
        case .narakenritu: return ["--","本校"]
        case .narakenrituika: return ["--","本校"]
        case .narajyoshi: return ["--","本校"]
        case .baikajyoshi: return ["--","本校"]
        case .hagoromokokusai: return ["--","本校"]
        case .hanazono: return ["--","本校"]
        case .hannan: return ["--","本キャンパス","南キャンパス","あべのハルカスキャンパス"]
        case .higasioosaka: return ["--","本校"]
        case .himeji: return ["--","本校"]
        case .himejidokkyou: return ["--","本校"]
        case .hyougo: return ["--","本校"]
        case .hyougoika: return ["--","西宮キャンパス","篠山キャンパス","神戸キャンパス"]
        case .hyogokyouiku: return ["--","本校"]
        case .hyogokenritu: return ["--","本校"]
        case .biwakogakuinn: return ["--","本校"]
        case .biwakoseikeisupotu: return ["--","本校"]
        case .biwakorihabirisennmonsyoku: return ["--","本校"]
        case .hukutiyamakouritu: return ["--","本校"]
        case .bukkyo: return ["--","紫野キャンパス","二条キャンパス","岩倉キャンパス","広沢キャンパス","園部キャンパス"]
        case .heiannjogakuinn: return ["--","京都キャパス","高槻キャンパス"]
        case .mie: return ["--","本校"]
        case .miekennritukanngo: return ["--","本校"]
        case .mukogawajyoshi: return ["--","中央キャンパス","浜甲子園キャンパス","上甲子園キャンパス","武庫女ステーションキャンパス","北摂キャンパス","本校"]
        case .meijikokusaiiryou: return ["--","本校"]
        case .momoyamagakuin: return ["--","本校"]
        case .momoyamagakuinkyoiku: return ["--","本校"]
        case .morinomiyairyou: return ["--","本校"]
        case .yamato: return ["--","本校"]
        case .yokkaiti: return ["--","本校"]
        case .yokkaitikanngoiryou: return ["--","本校"]
        case .Ritumeikan: return ["--","衣笠キャンパス","びわこ・くさつキャンパス","大阪いばらきキャンパス","朱雀キャンパス"]
        case .Ryukoku: return ["--","深草キャンパス","瀬田キャンパス","大宮キャンパス"]
        case .ryutukagaku: return ["--","本校"]
        case .wakayama: return ["--","本校"]
        case .wakayamakenrituika: return ["--","伏虎キャンパス","三葛キャンパス","紀三井寺キャンパス"]
        case .wakayamasinai: return ["--","本校"]
        case .wakayamarihabiritesyonsennmonnsyoku: return ["--","本校"]
        case .kannsaihukusikagaku: return ["--","本校"]
        case .kyotoitiritugeijyutu: return ["--","本校"]
        case .kyoutobijutukougei: return ["--","京都東山キャンパス"]
        }
    }
}
