//
//  University.swift
//  University
//
//  Created by 髙間洋平 on 2021/08/21.
//

import SwiftUI

enum KansaiUniversity: String, CaseIterable {
    case Ritumeikan // 立命館大学
    case Dousisya // 同志社大学
    case Kansai // 関西大学
    case Kansaigakuin // 関西学院大学
    case Kinki // 近畿大学
    case Kyotosangyou // 京都産業大学
    case Ryukoku // 龍谷大学
    case bukkyo // 佛教大学
    case kounan // 甲南大学
    case kansaigaikokugo // 関西外国語大学
    case kyotojyoshi // 京都女子大学
    case mukogawajyoshi // 武庫川女子大学
    case kyotogaikokugo // 京都外国語大学
    case osakakeizai // 大阪経済大学
    case koubejyosi // 神戸女子大学
    case kiou // 畿央大学
    case kyototatibana // 京都橘大学
    case otemon // 追手門大学
    case yamato // 大和大学
    case setunen // 摂南大学
    case osakasyoinjyoshi // 大阪松蔭女子大学
    case konanjyoshi // 甲南女子大学
    case kobegakuin // 神戸学院大学
    case tezukayama // 帝塚山大学
    case kyotoseika // 京都精華大学
    case kyotobunkyou // 京都文教大学
    case hannan // 阪南大学
    case momoyamagakuin // 桃山学院大学
    case kansaihukushi // 関西福祉大学
    case kyotogeijyutu // 京都芸術大学
    case kyotogeijyutukougei // 京都芸術工芸大学
    case osakakeizaihoka // 大阪経済法科大学
    case osakataiku // 大阪体育大学
    case osakasogohoiku // 大阪総合保育大学
    case kobetokiwa // 神戸常盤大学
    case osakakogyou // 大阪工業大学
    case osakasaigyou // 大阪産業大学
    case tenri // 天理大学
    case osakakokusai // 大阪国際大学
    case osakasyogyou // 大阪商業大学
    case osakaotani // 大阪大谷大学
    case momoyamagakuinkyoiku // 桃山学院教育大学
    case sonodegakuinjyoshi // 園田学院女子大学
    case nara // 奈良大学
    case kyotokokajyoshi // 京都光華女子大学
    case baikajyoshi // 梅花女子大学
    case kobesyoinjyoshigakuin // 神戸松蔭女子学院大学
    case wakayamasinai // 和歌山信愛大学
    case kyotosentankagaku // 京都先端科学大学
    case otemae // 大手前大学
    case kosien // 甲子園大学
    case kobesinwajyoshi // 神戸親和女子大学
    case ryutukagaku // 流通科学大学
    case naragakuen // 奈良学園大学
    case kyotonotorudamjyoshi // 京都ノートルダム女子大学
    case Nagoya // 名古屋大学
    case Nagoyakogyo // 名古屋工業大学
    case kyoto // 京都大学
    case osaka // 大阪大学
    case kobe // 神戸大学
    case osakakoritu // 大阪公立大学
    case kyotohuritu // 京都府立大学
    case kobeshigaikoukugo // 神戸市外国語大学
    case narajyoshi // 奈良女子大学
    case hyogokenritu // 兵庫県立大学
    case shiga // 滋賀大学
    case wakayama // 和歌山大学
    case gejyutubunkakankousenmonsyoku // 芸術文化観光専門職大学
    case narakenritu // 奈良県立大学
    case shigakenritu // 滋賀県立大学
    case kyotoshiritugeijyutu // 京都市立芸術大学
    case kyotokyoiku // 京都教育大学
    case osakakyoiku // 大阪教育大学
    case narakyoiku // 奈良教育大学
    case hyogokyouiku // 兵庫教育大学
    case hukutiyamakouritu // 福知山公立大学
    case kyotohurituika // 京都府立医科大学
    case shigaika // 滋賀医科大学
    case wakayamakenrituika // 和歌山県立医科大学
    case kyotokogeiseni // 京都工芸繊維大学
    case kobeshikango // 神戸市看護大学
    case narakenrituika // 奈良県立医科大学
    
    
    var name: String {
        switch self {
        case .Ritumeikan: return "立命館大学"
        case .Dousisya: return "同志社大学"
        case .Kansai: return "関西大学"
        case .Kansaigakuin: return "関西学院大学"
        case .Kinki: return "近畿大学"
        case .Kyotosangyou: return "京都産業大学"
        case .Ryukoku: return "龍谷大学"
        case .bukkyo: return "佛教大学"
        case .kounan: return "甲南大学"
        case .kansaigaikokugo: return "関西外国語大学"
        case .kyotojyoshi: return "京都女子大学"
        case .mukogawajyoshi: return "武庫川女子大学"
        case .kyotogaikokugo: return "京都外国語大学"
        case .osakakeizai: return "大阪経済大学"
        case .koubejyosi: return "神戸女子大学"
        case .kiou: return "畿央大学"
        case .kyototatibana: return "京都橘大学"
        case .otemon: return "追手門大学"
        case .yamato: return "大和大学"
        case .setunen: return "摂南大学"
        case .osakasyoinjyoshi: return "大阪松蔭女子大学"
        case .konanjyoshi: return "甲南女子大学"
        case .kobegakuin: return "神戸学院大学"
        case .tezukayama: return "帝塚山大学"
        case .kyotoseika: return "京都精華大学"
        case .kyotobunkyou: return "京都文教大学"
        case .hannan: return "阪南大学"
        case .momoyamagakuin: return "桃山学院大学"
        case .kansaihukushi: return "関西福祉大学"
        case .kyotogeijyutu: return "京都芸術大学"
        case .kyotogeijyutukougei: return "京都芸術工芸大学"
        case .osakakeizaihoka: return "大阪経済法科大学"
        case .osakataiku: return "大阪体育大学"
        case .osakasogohoiku: return "大阪総合保育大学"
        case .kobetokiwa: return "神戸常盤大学"
        case .osakakogyou: return "大阪工業大学"
        case .osakasaigyou: return "大阪産業大学"
        case .tenri: return "天理大学"
        case .osakakokusai: return "大阪国際大学"
        case .osakasyogyou: return "大阪商業大学"
        case .osakaotani: return "大阪大谷大学"
        case .momoyamagakuinkyoiku: return "桃山学院教育大学"
        case .sonodegakuinjyoshi: return "園田学院女子大学"
        case .nara: return "奈良大学"
        case .kyotokokajyoshi: return "京都光華女子大学"
        case .baikajyoshi: return "梅花女子大学"
        case .kobesyoinjyoshigakuin: return "神戸松蔭女子学院大学"
        case .wakayamasinai: return "和歌山信愛大学"
        case .kyotosentankagaku: return "京都先端科学大学"
        case .otemae: return "大手前大学"
        case .kosien: return "甲子園大学"
        case .kobesinwajyoshi: return "神戸親和女子大学"
        case .ryutukagaku: return "流通科学大学"
        case .naragakuen: return "奈良学園大学"
        case .kyotonotorudamjyoshi: return "京都ノートルダム女子大学"
        case .Nagoya: return "名古屋大学"
        case .Nagoyakogyo: return "名古屋工業大学"
        case .kyoto: return "京都大学"
        case .osaka: return "大阪大学"
        case .kobe: return "神戸大学"
        case .osakakoritu: return "大阪公立大学"
        case .kyotohuritu: return "京都府立大学"
        case .kobeshigaikoukugo: return "神戸市外国語大学"
        case .narajyoshi: return "奈良女子大学"
        case .hyogokenritu: return "兵庫県立大学"
        case .shiga: return "滋賀大学"
        case .wakayama: return "和歌山大学"
        case .gejyutubunkakankousenmonsyoku: return "芸術文化観光専門職大学"
        case .narakenritu: return "奈良県立大学"
        case .shigakenritu: return "滋賀県立大学"
        case .kyotoshiritugeijyutu: return "京都市立芸術大学"
        case .kyotokyoiku: return "京都教育大学"
        case .osakakyoiku: return "大阪教育大学"
        case .narakyoiku: return "奈良教育大学"
        case .hyogokyouiku: return "兵庫教育大学"
        case .hukutiyamakouritu: return "福知山公立大学"
        case .kyotohurituika: return "京都府立医科大学"
        case .shigaika: return "滋賀医科大学"
        case .wakayamakenrituika: return "和歌山県立医科大学"
        case .kyotokogeiseni: return "京都工芸繊維大学"
        case .kobeshikango: return "神戸市看護大学"
        case .narakenrituika: return "奈良県立医科大学"
            }
    }
    
    var description: [String] {
        switch self {
        case .Ritumeikan: return ["--","衣笠キャンパス","びわこ・くさつキャンパス","大阪いばらきキャンパス","朱雀キャンパス"]
        case .Dousisya: return ["--","今出川キャンパス","新町キャンパス","室町キャンパス","京田辺キャンパス","大阪サテライトキャンパス","東京サテライトキャンパス"]
        case .Kansai: return ["--","未設定"]
        case .Kansaigakuin: return ["--","未設定"]
        case .Kinki: return ["--","東大阪","大阪狭山キャンパス","奈良キャンパス","和歌山キャンパス","広島キャンパス","福岡キャンパス"]
        case .Kyotosangyou: return ["--","未設定"]
        case .Ryukoku: return ["--","深草キャンパス","瀬田キャンパス","大宮キャンパス"]
        case .bukkyo: return ["--","紫野キャンパス","二条キャンパス","岩倉キャンパス","広沢キャンパス","園部キャンパス"]
        case .kounan: return ["--","岡本キャンパス","西宮キャンパス","ポートアイランドキャンパス","白川台キャンパス"]
        case .kansaigaikokugo: return ["--","中宮キャンパス","御殿山キャンパス・グローバルタウン","片鉾キャンパス","学研都市キャンパス"]
        case .kyotojyoshi: return ["--","未設定"]
        case .mukogawajyoshi: return ["--","中央キャンパス","浜甲子園キャンパス","上甲子園キャンパス","武庫女ステーションキャンパス","北摂キャンパス"]
        case .kyotogaikokugo: return ["--","未設定"]
        case .osakakeizai: return ["--","大隅キャンパス","北浜キャンパス"]
        case .koubejyosi: return ["--","須磨キャンパス","ポートアイランドキャンパス","三宮キャンパス"]
        case .kiou: return ["--","未設定"]
        case .kyototatibana: return ["--","未設定"]
        case .otemon: return ["--","茨木安威","茨木総持寺"]
        case .yamato: return ["--","未設定"]
        case .setunen: return ["--","寝屋川キャンパス","枚方キャンパス"]
        case .osakasyoinjyoshi: return ["--","未設定"]
        case .konanjyoshi: return ["--","未設定"]
        case .kobegakuin: return ["--","ポートアイランドキャンパス","有瀬キャンパス"]
        case .tezukayama: return ["--","東生駒キャンパス","学園前キャンパス"]
        case .kyotoseika: return ["--","未設定"]
        case .kyotobunkyou: return ["--","未設定"]
        case .hannan: return ["--","本キャンパス","南キャンパス","あべのハルカスキャンパス"]
        case .momoyamagakuin: return ["--","未設定"]
        case .kansaihukushi: return ["--","未設定"]
        case .kyotogeijyutu: return ["--","未設定"]
        case .kyotogeijyutukougei: return ["--","未設定"]
        case .osakakeizaihoka: return ["--","花岡キャンパス","八尾駅前キャンパス"]
        case .osakataiku: return ["--","未設定"]
        case .osakasogohoiku: return ["--","未設定"]
        case .kobetokiwa: return ["--","未設定"]
        case .osakakogyou: return ["--","大宮キャンパス","梅田キャンパス","枚方キャンパス"]
        case .osakasaigyou: return ["--","中央キャンパス","東キャンパス","南キャンパス","生駒キャンパス"]
        case .tenri: return ["--","杣之内キャンパス","体育学部キャンパス"]
        case .osakakokusai: return ["--","未設定"]
        case .osakasyogyou: return ["--","未設定"]
        case .osakaotani: return ["--","未設定"]
        case .momoyamagakuinkyoiku: return ["--","未設定"]
        case .sonodegakuinjyoshi: return ["--","未設定"]
        case .nara: return ["--","未設定"]
        case .kyotokokajyoshi: return ["--","未設定"]
        case .baikajyoshi: return ["--","未設定"]
        case .kobesyoinjyoshigakuin: return ["--","未設定"]
        case .wakayamasinai: return ["--","未設定"]
        case .kyotosentankagaku: return ["--","太秦キャンパス","亀岡キャンパス"]
        case .otemae: return ["--","さくら夙川キャンパス","大阪大手前キャンパス"]
        case .kosien: return ["--","未設定"]
        case .kobesinwajyoshi: return ["--","未設定"]
        case .ryutukagaku: return ["--","未設定"]
        case .naragakuen: return ["--","三郷キャンパス","登美ヶ丘キャンパス"]
        case .kyotonotorudamjyoshi: return ["--","未設定"]
        case .Nagoya: return ["--","東山キャンパス","鶴舞キャンパス","大幸キャンパス"]
        case .Nagoyakogyo: return ["--","御器所キャンパス"]
        case .kyoto: return ["--","吉田キャンパス","宇治キャンパス","桂キャンパス"]
        case .osaka: return ["--","豊中キャンパス","吹田キャンパス","箕面キャンパス"]
        case .kobe: return ["--","六甲台第1キャンパス","六甲台第2キャンパス","鶴甲第1キャンパス","鶴甲第2キャンパス"]
        case .osakakoritu: return ["--","杉元キャンパス","阿倍野キャンパス","羽曳野キャンパス","中百舌鳥キャンパス","りんくうキャンパス","梅田サテライト"]
        case .kyotohuritu: return ["--","未設定"]
        case .kobeshigaikoukugo: return ["--","未設定"]
        case .narajyoshi: return ["--","未設定"]
        case .hyogokenritu: return ["--","未設定"]
        case .shiga: return ["--","大津キャンパス","彦根キャンパス"]
        case .wakayama: return ["--","未設定"]
        case .gejyutubunkakankousenmonsyoku: return ["--","未設定"]
        case .narakenritu: return ["--","未設定"]
        case .shigakenritu: return ["--","未設定"]
        case .kyotoshiritugeijyutu: return ["--","未設定"]
        case .kyotokyoiku: return ["--","未設定"]
        case .osakakyoiku: return ["--","天王寺キャンパス","柏原キャンパス"]
        case .narakyoiku: return ["--","未設定"]
        case .hyogokyouiku: return ["--","未設定"]
        case .hukutiyamakouritu: return ["--","未設定"]
        case .kyotohurituika: return ["--","広小路キャンパス","河原町キャンパス","下鴨キャンパス"]
        case .shigaika: return ["--","未設定"]
        case .wakayamakenrituika: return ["--","伏虎キャンパス","三葛キャンパス","紀三井寺キャンパス"]
        case .kyotokogeiseni: return ["--","松ヶ崎キャンパス","福知山キャンパス"]
        case .kobeshikango: return ["--","未設定"]
        case .narakenrituika: return ["--","未設定"]
        }
    }
}
