//
//  KantoUniversity.swift
//  CaptionCalendar
//
//  Created by 髙間洋平 on 2021/09/21.
//

import SwiftUI

enum KantoUniversity: String, CaseIterable {
    case Ibaraki // 茨城大学
    case Tsukuba // 筑波大学
    case Tsukubagijutsu // 筑波技術大学
    case Utsunomiya // 宇都宮大学
    case Gunma // 群馬大学
    case Saitama // 埼玉大学
    case Tiba // 千葉大学
    case Otyanomizujoshi // お茶の水女子大学
    case Denkitsusin // 電気通信大学
    case Tokyo // 東京大学
    case Tokyoikashika // 東京医科歯科大学
    case Tokyogaikokugo // 東京外国語大学
    case Tokyokaiyou // 東京海洋大学
    case Tokyogakugei // 東京学芸大学
    case Tokyogeijutsu // 東京藝術大学
    case Tokyokogyo // 東京工業大学
    case Tokyonouko // 東京農工大学
    case Hitotsubashi // 一橋大学
    case Yokohamakokuritsu // 横浜国立大学
    case Ibarakikenritsuiryo // 茨城県立医療大学
    case Gunmakenkoukagaku // 群馬健康科学大学
    case Gunmakenritsujoshi // 群馬県立女子大学
    case Takasakikeizai // 高崎経済大学
    case Maehashikouka // 前橋工科大学
    case Saitamakenritsu // 埼玉県立大学
    case Tibakenritsuhokeniryo // 千葉県立保健医療大学
    case Tokyotoritsu // 東京都立大学
    case Kanagawakenritsuhokenhukushi // 神奈川県立保健福祉大学
    case Kawasakiitiritsukango // 川崎市立看護大学
    case Yokohamaitiritsu // 横浜市立大学
    case Ibarakikirisutokyo // 茨城キリスト教大学
    case Tsukubagakuin // 筑波学院大学
    case Tsukubakokusai // つくば国際大学
    case Tokiwa // 常磐大学
    case Nihonwerunesusupotsu // 日本ウェルネススポーツ大学
    case Ryutsukeizai // 流通経済大学
    case Ashikaga // 足利大学
    case Utsunomiyakyowa // 宇都宮共和大学
    case Kokusaiiryouhukushi // 国際医療福祉大学
    case Sakushingakuin // 作新学院大学
    case Jitiika // 自治医科大学
    case Dokkyoika // 獨協医科大学
    case Hakuou // 白鴎大学
    case Bunseigeijutsu // 文星芸術大学
    case Ikuei // 育英大学
    case Kantogakuen // 関東学園大学
    case Kyoaigakuenmaehashikokusai // 共愛学園前橋国際大学
    case Kiryu // 桐生大学
    case Gunmairyohukushi // 群馬医療福祉大学
    case Gunmapasu // 群馬パース大学
    case Jobu // 上武大学
    case Takasakikenkouhukushi // 高崎健康福祉大学
    case Takasakisyouka // 高崎商科大学
    case Urawa // 浦和大学
    case Kyouei // 共栄大学
    case Saitamaika // 埼玉医科大学
    case Saitamagakuen // 埼玉学園大学
    case Saitamakogyo // 埼玉工業大学
    case Jumonjigakuenjoshi // 十文字学園女子大学
    case Josei // 城西大学
    case Syobigakuen // 尚美学園大学
    case Joshieiyou // 女子栄養大学
    case Surugadai // 駿河台大学
    case Seigakuin // 聖学院大学
    case Seibubunri // 西武文理大学
    case Tokyokokusai // 東京国際大学
    case Touto // 東都大学
    case Touhouongaku // 東邦音楽大学
    case Dokkyou // 獨協大学
    case Nihoniryokagaku // 日本医療科学大学
    case Nihonkogyo // 日本工業大学
    case Nihonhokeniryo // 日本保健医療大学
    case Nihonyakka // 日本薬科大学
    case Ningensogokagaku // 人間総合科学大学
    case Bunkyo // 文教大学
    case Heiseikokusai // 平成国際大学
    case Musashinogakuin // 武蔵野学院大学
    case Meikai // 明海大学
    case Monotsukuri // ものつくり大学
    case Aikokugakuen // 愛国学園大学
    case Uekusagakuen // 植草学園大学
    case Edokawa // 江戸川大学
    case Kaitikokusai // 開智国際大学
    case Kamedairyo // 亀田医療大学
    case Kawamuragakuenjoshi // 川村学園女子大学
    case Kandagaikokugo // 神田外国語大学
    case Keiai // 敬愛大学
    case Kokusaibudo // 国際武道大学
    case Sanikugakuin // 三育学院大学
    case Syumei // 秀明大学
    case Syukutoku // 淑徳大学
    case Joseikokusai // 城西国際大学
    case Seitoku // 聖徳大学
    case Seiwa // 清和大学
    case Tibakagaku // 千葉科学大学
    case Tibakeizai // 千葉経済大学
    case Tibakougyou // 千葉工業大学
    case Tibasyouka // 千葉商科大学
    case Tyuougakuin // 中央学院大学
    case Tokyokirisutokyo // 東京基督教大学
    case Tokyojouhou // 東京情報大学
    case Ryotokuji // 了徳寺大学
    case Reitaku // 麗澤大学
    case Wayojoshi // 和洋女子大学
    case Aoyamagakuin // 青山学院大学
    case Ajia // 亜細亜大学
    case Atomigakuenjoshi // 跡見学園女子大学
    case Oubirin // 桜美林大学
    case Ootumajoshi // 大妻女子大学
    case Kaetsu // 嘉悦大学
    case Gakusyuin // 学習院大学
    case Gakusyuinjoshi // 学習院女子大学
    case Kitasto // 北里大学
    case Kyoritsujoshi // 共立女子大学
    case Kyorin // 杏林大学
    case Kokuritsuongaku // 国立音楽大学
    case Keiou // 慶応大学
    case Keisenjogakuen // 恵泉女学園大学
    case Kougakuin // 工学院大学
    case Kokugakuin // 國學院大学
    case Kokusaikirisutokyo // 国際基督教大学
    case Kokushikan // 国士舘大学
    case Kodomokyoikuhousen // こども教育宝仙大学
    case Komazawa // 駒澤大学
    case Komazawajoshi // 駒沢女子大学
    case Sangyonouritsu // 産業能率大学
    case Jissenjoshi // 実践女子大学
    case Shibaurakougyo // 芝浦工業大学
    case Juntendo // 順天堂大学
    case Jochi // 上智大学
    case Johoukeieiinobesyonsenmonsyoku // 情報経営イノベーション専門職大学
    case Syowa // 昭和大学
    case Syowajoshi // 昭和女子大学
    case Syowayakka // 昭和薬科大学
    case Joshibijutsu // 女子美術大学
    case Shiraumegakuen // 白梅学園大学
    case Shirayurijoshi // 白百合女子大学
    case Suginohukusyoku // 杉野服飾大学
    case Seikei // 成蹊大学
    case Seijo // 成城大学
    case Seishinjoshi // 聖心女子大学
    case Seisenjoshi // 清泉女子大学
    case Seirukakokusai // 聖路加国際大学
    case Sensyu // 専修大学
    case Souka // 創価大学
    case Taisyo // 大正大学
    case Daitobunka // 大東文化大学
    case Takachiho // 高千穂大学
    case Takusyoku // 拓殖大学
    case Tama // 多摩大学
    case Tamagawa // 玉川大学
    case Tamabijutsu // 多摩美術大学
    case Chuo // 中央大学
    case Tsudajuku // 津田塾大学
    case Teikyo // 帝京大学
    case Teikyokagaku // 帝京科学大学
    case Teikyoheisei // 帝京平成大学
    case Dejitaruhollywood // デジタルハリウッド大学
    case Tokai // 東海大学
    case Tokyoariakeiryo // 東京有明医療大学
    case Tokyoika // 東京医科大学
    case Tokyoiryogakuin // 東京医療学院大学
    case Tokyoiryohoken // 東京医療保健大学
    case Tokyoongaku // 東京音楽大学
    case Tokyokasei // 東京家政大学
    case Tokyokaseigakuin // 東京家政学院大学
    case Tokyokeizai // 東京経済大学
    case Tokyokouka // 東京工科大学
    case Tokyokougei // 東京工芸大学
    case Tokyoshika // 東京歯科大学
    case Tokyojikeikaiika // 東京慈恵会医科大学
    case Tokyojunshin // 東京純心大学
    case Tokyojoshi // 東京女子大学
    case Tokyojoshiika // 東京女子医科大学
    case Tokyojoshitaiiku // 東京女子体育大学
    case Tokyoshingaku // 東京神学大学
    case Tokyoseiei // 東京聖栄大学
    case Tokyoseitoku // 東京成徳大学
    case Tokyozoukei // 東京造形大学
    case Tokyodenki // 東京電機大学
    case Tokyotoshi // 東京都市大学
    case Tokyonougyo // 東京農業大学
    case Tokyohukushi // 東京福祉大学
    case Tokyofuji // 東京富士大学
    case Tokyohokeniryosenmonsyoku // 東京保健医療専門職大学
    case Tokyomirai // 東京未来大学
    case Tokyoyakka // 東京薬科大学
    case Tokyorika // 東京理科大学
    case Toho // 東邦大学
    case Tohogakuen // 東朋学園大学
    case Toyo // 東洋大学
    case Nisyogakusya // 二松学舎大学
    case Nihonsekijuujikango // 日本赤十字看護大学
    case Nihon // 日本大学
    case Nihonika // 日本医科大学
    case Nihonshika // 日本歯科大学
    case Nihonsyakaijigyo // 日本社会事業大学
    case Nihonjuuiseimeikagaku // 日本獣医生命科学医大学
    case Nihonjoshi // 日本女子大学
    case Nihonjoshitaiiku // 日本女子体育大学
    case Nihontaiiku // 日本体育大学
    case Nihonbunka // 日本文化大学
    case Bunkagakuen // 文化学園大学
    case Bunkyogakuin // 文京学院大学
    case Housei // 法政大学
    case Hoshiyakka // 星薬科大学
    case Musashi // 武蔵大学
    case Musashino // 武蔵野大学
    case Musashinoongaku // 武蔵野音楽大学
    case Musashinobijutu // 武蔵野美術大学
    case Meiji // 明治大学
    case Meijigakuin // 明治学院大学
    case Meijiyakka // 明治薬科大学
    case Meisei // 明星大学
    case Yamazakidoubutsukango // ヤマザキ動物看護大学
    case Rikkyo // 立教大学
    case Rissyo // 立正大学
    case Ruterugakuin // ルーテル学院大学
    case Wako // 和光大学
    case Waseda // 早稲田大学
    case Azabu // 麻布大学
    case Kanagawa // 神奈川大学
    case Kanagawakouka // 神奈川工科大学
    case Kanagawasika // 神奈川歯科大学
    case Kamakurajoshi // 鎌倉女子大学
    case Kantogakuin // 関東学院大学
    case Sagamijoshi // 相模女子大学
    case Syoin // 松蔭大学
    case Toyoeiwajogakuin // 東洋英和女学院大学
    case Nihoneiga // 日本映画大学
    case Ferisujogakuin // フェリス女学院大学
    case Yokohamasyouka // 横浜商科大学
    case Yokohamasouei // 横浜創英大学
    case Yokohamabijutu // 横浜美術大学
    case Yokohamayakka // 横浜薬科大学
    
    var name: String {
        switch self {
        case .Ibaraki: return "茨城大学"
        case .Tsukuba: return "筑波大学"
        case .Tsukubagijutsu: return "筑波技術大学"
        case .Utsunomiya: return "宇都宮大学"
        case .Gunma: return "群馬大学"
        case .Saitama: return "埼玉大学"
        case .Tiba: return "千葉大学"
        case .Otyanomizujoshi: return "お茶の水女子大学"
        case .Denkitsusin: return "電気通信大学"
        case .Tokyo: return "東京大学"
        case .Tokyoikashika: return "東京医科歯科大学"
        case .Tokyogaikokugo: return "東京外国語大学"
        case .Tokyokaiyou: return "東京海洋大学"
        case .Tokyogakugei: return "東京学芸大学"
        case .Tokyogeijutsu: return "東京藝術大学"
        case .Tokyokogyo: return "東京工業大学"
        case .Tokyonouko: return "東京農工大学"
        case .Hitotsubashi: return "一橋大学"
        case .Yokohamakokuritsu: return "横浜国立大学"
        case .Ibarakikenritsuiryo: return "茨城県立医療大学"
        case .Gunmakenkoukagaku: return "群馬健康科学大学"
        case .Gunmakenritsujoshi: return "群馬県立女子大学"
        case .Takasakikeizai: return "高崎経済大学"
        case .Maehashikouka: return "前橋工科大学"
        case .Saitamakenritsu: return "埼玉県立大学"
        case .Tibakenritsuhokeniryo: return "千葉県立保健医療大学"
        case .Tokyotoritsu: return "東京都立大学"
        case .Kanagawakenritsuhokenhukushi: return "神奈川県立保健福祉大学"
        case .Kawasakiitiritsukango: return "川崎市立看護大学"
        case .Yokohamaitiritsu: return "横浜市立大学"
        case .Ibarakikirisutokyo: return "茨城教キリスト大学"
        case .Tsukubagakuin: return "筑波学院大学"
        case .Tsukubakokusai: return "つくば国際大学"
        case .Tokiwa: return "常磐大学"
        case .Nihonwerunesusupotsu: return "日本ウェルネススポーツ大学"
        case .Ryutsukeizai: return "流通経済大学"
        case .Ashikaga: return "足利大学"
        case .Utsunomiyakyowa: return "宇都宮共和大学"
        case .Kokusaiiryouhukushi: return "国際医療福祉大学"
        case .Sakushingakuin: return "作新学院大学"
        case .Jitiika: return "自治医科大学"
        case .Dokkyoika: return "獨協医科大学"
        case .Hakuou: return "白鴎大学"
        case .Bunseigeijutsu: return "文星芸術大学"
        case .Ikuei: return "育英大学"
        case .Kantogakuen: return "関東学園大学"
        case .Kyoaigakuenmaehashikokusai: return "共愛学園前橋国際大学"
        case .Kiryu: return "桐生大学"
        case .Gunmairyohukushi: return "群馬医療福祉大学"
        case .Gunmapasu: return "群馬パース大学"
        case .Jobu: return "上武大学"
        case .Takasakikenkouhukushi: return "高崎健康福祉大学"
        case .Takasakisyouka: return "高崎商科大学"
        case .Urawa: return "浦和大学"
        case .Kyouei: return "共栄大学"
        case .Saitamaika: return "埼玉医科大学"
        case .Saitamagakuen: return "埼玉学園大学"
        case .Saitamakogyo: return "埼玉工業大学"
        case .Jumonjigakuenjoshi: return "十文字学園女子大学"
        case .Josei: return "城西大学"
        case .Syobigakuen: return "尚美学園大学"
        case .Joshieiyou: return "女子栄養大学"
        case .Surugadai: return "駿河台大学"
        case .Seigakuin: return "聖学院大学"
        case .Seibubunri: return "西武文理大学"
        case .Tokyokokusai: return "東京国際大学"
        case .Touto: return "東都大学"
        case .Touhouongaku: return "東邦音楽大学"
        case .Dokkyou: return "獨協大学"
        case .Nihoniryokagaku: return "日本医療科学大学"
        case .Nihonkogyo: return "日本工業大学"
        case .Nihonhokeniryo: return "日本保健医療大学"
        case .Nihonyakka: return "日本薬科大学"
        case .Ningensogokagaku: return "人間総合科学大学"
        case .Bunkyo: return "文教大学"
        case .Heiseikokusai: return "平成国際大学"
        case .Musashinogakuin: return "武蔵野学院大学"
        case .Meikai: return "明海大学"
        case .Monotsukuri: return "ものつくり大学"
        case .Aikokugakuen: return "愛国学園大学"
        case .Uekusagakuen: return "植草学園大学"
        case .Edokawa: return "江戸川大学"
        case .Kaitikokusai: return "開智国際大学"
        case .Kamedairyo: return "亀田医療大学"
        case .Kawamuragakuenjoshi: return "川村学園女子大学"
        case .Kandagaikokugo: return "神田外国語大学"
        case .Keiai: return "敬愛大学"
        case .Kokusaibudo: return "国際武道大学"
        case .Sanikugakuin: return "三育学院大学"
        case .Syumei: return "秀明大学"
        case .Syukutoku: return "淑徳大学"
        case .Joseikokusai: return "城西国際大学"
        case .Seitoku: return "聖徳大学"
        case .Seiwa: return "清和大学"
        case .Tibakagaku: return "千葉科学大学"
        case .Tibakeizai: return "千葉経済大学"
        case .Tibakougyou: return "千葉工業大学"
        case .Tibasyouka: return "千葉商科大学"
        case .Tyuougakuin: return "中央学院大学"
        case .Tokyokirisutokyo: return "東京基督教大学"
        case .Tokyojouhou: return "東京情報大学"
        case .Ryotokuji: return "了徳寺大学"
        case .Reitaku: return "麗澤大学"
        case .Wayojoshi: return "和洋女子大学"
        case .Aoyamagakuin: return "青山学院大学"
        case .Ajia: return "亜細亜大学"
        case .Atomigakuenjoshi: return "跡見学園女子大学"
        case .Oubirin: return "桜美林大学"
        case .Ootumajoshi: return "大妻女子大学"
        case .Kaetsu: return "嘉悦大学"
        case .Gakusyuin: return "学習院大学"
        case .Gakusyuinjoshi: return "学習院女子大学"
        case .Kitasto: return "北里大学"
        case .Kyoritsujoshi: return "共立女子大学"
        case .Kyorin: return "杏林大学"
        case .Kokuritsuongaku: return "国立音楽大学"
        case .Keiou: return "慶応大学"
        case .Keisenjogakuen: return "恵泉女学園大学"
        case .Kougakuin: return "工学院大学"
        case .Kokugakuin: return "國學院大学"
        case .Kokusaikirisutokyo: return "国際基督教大学"
        case .Kokushikan: return "国士舘大学"
        case .Kodomokyoikuhousen: return "こども教育宝仙大学"
        case .Komazawa: return "駒澤大学"
        case .Komazawajoshi: return "駒沢女子大学"
        case .Sangyonouritsu: return "産業能率大学"
        case .Jissenjoshi: return "実践女子大学"
        case .Shibaurakougyo: return "芝浦工業大学"
        case .Juntendo: return "順天堂大学"
        case .Jochi: return "上智大学"
        case .Johoukeieiinobesyonsenmonsyoku: return "情報経営イノベーション専門大学"
        case .Syowa: return "昭和大学"
        case .Syowajoshi: return "昭和女子大学"
        case .Syowayakka: return "昭和薬科大学"
        case .Joshibijutsu: return "女子美術大学"
        case .Shiraumegakuen: return "白梅学園大学"
        case .Shirayurijoshi: return "白百合女子大学"
        case .Suginohukusyoku: return "杉野服飾大学"
        case .Seikei: return "成蹊大学"
        case .Seijo: return "成城大学"
        case .Seishinjoshi: return "聖心女子大学"
        case .Seisenjoshi: return "清泉女子大学"
        case .Seirukakokusai: return "聖路加国際大学"
        case .Sensyu: return "専修大学"
        case .Souka: return "創価大学"
        case .Taisyo: return "大正大学"
        case .Daitobunka: return "大東文化大学"
        case .Takachiho: return "高千穂大学"
        case .Takusyoku: return "拓殖大学"
        case .Tama: return "多摩大学"
        case .Tamagawa: return "玉川大学"
        case .Tamabijutsu: return "多摩美術大学"
        case .Chuo: return "中央大学"
        case .Tsudajuku: return "津田塾大学"
        case .Teikyo: return "帝京大学"
        case .Teikyokagaku: return "帝京科学大学"
        case .Teikyoheisei: return "帝京平成大学"
        case .Dejitaruhollywood: return "デジタルハリウッド大学"
        case .Tokai: return "東海大学"
        case .Tokyoariakeiryo: return "東京有明医療大学"
        case .Tokyoika: return "東京医科大学"
        case .Tokyoiryogakuin: return "東京医療学院大学"
        case .Tokyoiryohoken: return "東京医療保健大学"
        case .Tokyoongaku: return "東京音楽大学"
        case .Tokyokasei: return "東京家政大学"
        case .Tokyokaseigakuin: return "東京家政学院大学"
        case .Tokyokeizai: return "東京経済大学"
        case .Tokyokouka: return "東京工科大学"
        case .Tokyokougei: return "東京工芸大学"
        case .Tokyoshika: return "東京歯科大学"
        case .Tokyojikeikaiika: return "東京慈恵会医科大学"
        case .Tokyojunshin: return "東京純心大学"
        case .Tokyojoshi: return "東京女子大学"
        case .Tokyojoshiika: return "東京女子医科大学"
        case .Tokyojoshitaiiku: return "東京女子体育大学"
        case .Tokyoshingaku: return "東京神学大学"
        case .Tokyoseiei: return "東京聖栄大学"
        case .Tokyoseitoku: return "東京成徳大学"
        case .Tokyozoukei: return "東京造形大学"
        case .Tokyodenki: return "東京電機大学"
        case .Tokyotoshi: return "東京都市大学"
        case .Tokyonougyo: return "東京農業大学"
        case .Tokyohukushi: return "東京福祉大学"
        case .Tokyofuji: return "東京富士大学"
        case .Tokyohokeniryosenmonsyoku: return "東京保健医療専門職大学"
        case .Tokyomirai: return "東京未来大学"
        case .Tokyoyakka: return "東京薬科大学"
        case .Tokyorika: return "東京理科大学"
        case .Toho: return "東邦大学"
        case .Tohogakuen: return "桐朋学園大学"
        case .Toyo: return "東洋大学"
        case .Nisyogakusya: return "二松学舎大学"
        case .Nihonsekijuujikango: return "日本赤十字看護大学"
        case .Nihon: return "日本大学"
        case .Nihonika: return "日本医科大学"
        case .Nihonshika: return "日本歯科大学"
        case .Nihonsyakaijigyo: return "日本社会事業大学"
        case .Nihonjuuiseimeikagaku: return "日本獣医生命科学医大学"
        case .Nihonjoshi: return "日本女子大学"
        case .Nihonjoshitaiiku: return "日本女子体育大学"
        case .Nihontaiiku: return "日本体育大学"
        case .Nihonbunka: return "日本文化大学"
        case .Bunkagakuen: return "文化学園大学"
        case .Bunkyogakuin: return "文京学院大学"
        case .Housei: return "法政大学"
        case .Hoshiyakka: return "星薬科大学"
        case .Musashi: return "武蔵大学"
        case .Musashino: return "武蔵野大学"
        case .Musashinoongaku: return "武蔵野音楽大学"
        case .Musashinobijutu: return "武蔵野美術大学"
        case .Meiji: return "明治大学"
        case .Meijigakuin: return "明治学院大学"
        case .Meijiyakka: return "明治薬科大学"
        case .Meisei: return "明星大学"
        case .Yamazakidoubutsukango: return "ヤマザキ動物看護大学"
        case .Rikkyo: return "立教大学"
        case .Rissyo: return "立正大学"
        case .Ruterugakuin: return "ルーテル学院大学"
        case .Wako: return "和光大学"
        case .Waseda: return "早稲田大学"
        case .Azabu: return "麻布大学"
        case .Kanagawa: return "神奈川大学"
        case .Kanagawakouka: return "神奈川工科大学"
        case .Kanagawasika: return "神奈川歯科大学"
        case .Kamakurajoshi: return "鎌倉女子大学"
        case .Kantogakuin: return "関東学院大学"
        case .Sagamijoshi: return "相模女子大学"
        case .Syoin: return "松蔭大学"
        case .Toyoeiwajogakuin: return "東洋英和学院大学"
        case .Nihoneiga: return "日本映画大学"
        case .Ferisujogakuin: return "フェリス女学院大学"
        case .Yokohamasyouka: return "横浜商科大学"
        case .Yokohamasouei: return "横浜創英大学"
        case .Yokohamabijutu: return "横浜美術大学"
        case .Yokohamayakka: return "横浜薬科大学"
        }
    }
    
    var description: [String] {
        switch self {
        case .Ibaraki: return ["--","水戸キャンパス","日立キャンパス","阿見キャンパス","水戸駅南サテライト"]
        case .Tsukuba: return ["--","筑波キャンパス","東京キャンパス"]
        case .Tsukubagijutsu: return ["--","春日キャンパス","天久保キャンパス"]
        case .Utsunomiya: return ["--","峰キャンパス","陽東キャンパス"]
        case .Gunma: return ["--","荒牧キャンパス","昭和キャンパス","桐生キャンパス","太田キャンパス"]
        case .Saitama: return ["--","本校","サテライトキャンパス"]
        case .Tiba: return ["--","西千葉キャンパス","亥鼻キャンパス","松戸キャンパス","柏の葉キャンパス","墨田サテライトキャンパス"]
        case .Otyanomizujoshi: return ["--","本校"]
        case .Denkitsusin: return ["--","本校"]
        case .Tokyo: return ["--","本郷キャンパス","駒場キャンパス"]
        case .Tokyoikashika: return ["--","湯島・駿河台キャンパス","国府台キャンパス"]
        case .Tokyogaikokugo: return ["--","府中キャンパス","本郷サテライト"]
        case .Tokyokaiyou: return ["--","品川キャンパス","越中島キャンパス"]
        case .Tokyogakugei: return ["--","本校"]
        case .Tokyogeijutsu: return ["--","上野キャンパス","取手キャンパス","横浜キャンパス","千住キャンパス"]
        case .Tokyokogyo: return ["--","大岡山キャンパス","すずかけ台キャンパス","田町キャンパス"]
        case .Tokyonouko: return ["--","府中キャンパス","小金井キャンパス"]
        case .Hitotsubashi: return ["--","国立キャンパス","小平国際キャンパス","千代田キャンパス"]
        case .Yokohamakokuritsu: return ["--","常磐台キャンパス","みなとみらいキャンパス"]
        case .Ibarakikenritsuiryo: return ["--","本校"]
        case .Gunmakenkoukagaku: return ["--","本校"]
        case .Gunmakenritsujoshi: return ["--","本校"]
        case .Takasakikeizai: return ["--","本校"]
        case .Maehashikouka: return ["--","本校"]
        case .Saitamakenritsu: return ["--","本校"]
        case .Tibakenritsuhokeniryo: return ["--","幕張キャンパス","仁戸名キャンパス"]
        case .Tokyotoritsu: return ["--","日野キャンパス","南大沢キャンパス","飯田橋キャンパス","荒川キャンパス","晴海キャンパス","秋葉原サテライトキャンパス","丸の内キャンパス"]
        case .Kanagawakenritsuhokenhukushi: return ["--","横須賀キャンパス","横浜(二俣川)キャンパス","川崎(殿町)キャンパス"]
        case .Kawasakiitiritsukango: return ["--","本校"]
        case .Yokohamaitiritsu: return ["--","福浦キャンパス","金沢八景キャンパス"]
        case .Ibarakikirisutokyo: return ["--","本校"]
        case .Tsukubagakuin: return ["--","本校"]
        case .Tsukubakokusai: return ["--","つくば国際大学キャンパス","第二キャンパス"]
        case .Tokiwa: return ["--","見和キャンパス","桜の郷キャンパス"]
        case .Nihonwerunesusupotsu: return ["--","一号館","東京サテライトキャンパス","北九州サテライトキャンパス","沖縄キャンパス"]
        case .Ryutsukeizai: return ["--","龍ケ崎キャンパス","新松戸キャンパス"]
        case .Ashikaga: return ["--","大前キャンパス","本城キャンパス"]
        case .Utsunomiyakyowa: return ["--","宇都宮シティキャンパス","長坂キャンパス","那須キャンパス"]
        case .Kokusaiiryouhukushi: return ["--","小田原キャンパス","成田キャンパス","東京赤坂キャンパス","小田原キャンパス","大川キャンパス"]
        case .Sakushingakuin: return ["--","本校"]
        case .Jitiika: return ["--","本校"]
        case .Dokkyoika: return ["--","本校"]
        case .Hakuou: return ["--","本キャンパス","大行寺キャンパス"]
        case .Bunseigeijutsu: return ["--","本校"]
        case .Ikuei: return ["--","本校"]
        case .Kantogakuen: return ["--","本校"]
        case .Kyoaigakuenmaehashikokusai: return ["--","本校"]
        case .Kiryu: return ["--","本校"]
        case .Gunmairyohukushi: return ["--","前橋キャンパス","藤岡キャンパス","本町キャンパス"]
        case .Gunmapasu: return ["--","本校"]
        case .Jobu: return ["--","高崎キャンパス","伊勢崎キャンパス"]
        case .Takasakikenkouhukushi: return ["--","本校"]
        case .Takasakisyouka: return ["--","本校"]
        case .Urawa: return ["--","本校"]
        case .Kyouei: return ["--","本校"]
        case .Saitamaika: return ["--","毛呂山キャンパス","日高キャンパス","川角キャンパス","川越キャンパス","川越ビル"]
        case .Saitamagakuen: return ["--","本校"]
        case .Saitamakogyo: return ["--","本校"]
        case .Jumonjigakuenjoshi: return ["--","本校"]
        case .Josei: return ["--","坂戸キャンパス","東京紀尾井町キャンパス"]
        case .Syobigakuen: return ["--","本校"]
        case .Joshieiyou: return ["--","坂戸キャンパス","駒込キャンパス"]
        case .Surugadai: return ["--","本校"]
        case .Seigakuin: return ["--","本校"]
        case .Seibubunri: return ["--","本校"]
        case .Tokyokokusai: return ["--","第１キャンパス","第２キャンパス","坂戸キャンパス","高田馬場サテライト"]
        case .Touto: return ["--","深谷キャンパス","幕張キャンパス","沼津キャンパス"]
        case .Touhouongaku: return ["--","文教キャンパス","川越キャンパス"]
        case .Dokkyou: return ["--","本校"]
        case .Nihoniryokagaku: return ["--","本校"]
        case .Nihonkogyo: return ["--","埼玉キャンパス","神田キャンパス"]
        case .Nihonhokeniryo: return ["--","幸手北キャンパス","幸手南キャンパス"]
        case .Nihonyakka: return ["--","さいたまキャンパス","お茶の水キャンパス"]
        case .Ningensogokagaku: return ["--","蓮田キャンパス","岩槻キャンパス","東京サテライト"]
        case .Bunkyo: return ["--","越谷キャンパス","湘南キャンパス","東京あだちキャンパス","旗の台キャンパス","石川台キャンパス"]
        case .Heiseikokusai: return ["--","加須キャンパス","大学院大宮サテライトキャンパス"]
        case .Musashinogakuin: return ["--","本校"]
        case .Meikai: return ["--","浦安キャンパス","坂戸キャンパス"]
        case .Monotsukuri: return ["--","本校"]
        case .Aikokugakuen: return ["--","本校"]
        case .Uekusagakuen: return ["--","本校"]
        case .Edokawa: return ["--","本校"]
        case .Kaitikokusai: return ["--","本校"]
        case .Kamedairyo: return ["--","横渚キャンパス","東町キャンパス"]
        case .Kawamuragakuenjoshi: return ["--","我孫子キャンパス","目白キャンパス"]
        case .Kandagaikokugo: return ["--","本校"]
        case .Keiai: return ["--","稲毛キャンパス","佐倉キャンパス"]
        case .Kokusaibudo: return ["--","本校"]
        case .Sanikugakuin: return ["--","大多喜キャンパス","東京校舎"]
        case .Syumei: return ["--","本校"]
        case .Syukutoku: return ["--","千葉キャンパス","千葉第二キャンパス","埼玉キャンパス","東京キャンパス"]
        case .Joseikokusai: return ["--","千葉東金キャンパス","東京紀尾井町キャンパス","安房キャンパス"]
        case .Seitoku: return ["--","本校"]
        case .Seiwa: return ["--","本校"]
        case .Tibakagaku: return ["--","本部キャンパス","マリーナキャンパス"]
        case .Tibakeizai: return ["--","本校"]
        case .Tibakougyou: return ["--","津田沼キャンパス","新習キャンパス","東京スカイツリータウン®キャンパス"]
        case .Tibasyouka: return ["--","市川キャンパス","丸の内サテライトキャンパス"]
        case .Tyuougakuin: return ["--","本校"]
        case .Tokyokirisutokyo: return ["--","本校"]
        case .Tokyojouhou: return ["--","本校"]
        case .Ryotokuji: return ["--","本校"]
        case .Reitaku: return ["--","本校"]
        case .Wayojoshi: return ["--","本校"]
        case .Aoyamagakuin: return ["--","青山キャンパス","相模原キャンパス"]
        case .Ajia: return ["--","武蔵野キャンパス","日の出キャンパス"]
        case .Atomigakuenjoshi: return ["--","文教キャンパス","新座キャンパス"]
        case .Oubirin: return ["--","町田キャンパス","新宿キャンパス","東京ひなたやまキャンパス","プラネット淵野辺キャンパス","千駄ヶ谷キャパス","多摩アカデミーヒルズ(多摩キャンパス)"]
        case .Ootumajoshi: return ["--","多摩キャンパス","千代田キャンパス"]
        case .Kaetsu: return ["--","本校"]
        case .Gakusyuin: return ["--","本校"]
        case .Gakusyuinjoshi: return ["--","本校"]
        case .Kitasto: return ["--","白金キャンパス","相模原キャンパス","十和田キャンパス","北本キャンパス","新潟キャンパス"]
        case .Kyoritsujoshi: return ["--","神田一ツ橋キャンパス","パノラマキャンパス","八王子キャンパス"]
        case .Kyorin: return ["--","三鷹キャンパス","井の頭キャンパス","八王子キャンパス"]
        case .Kokuritsuongaku: return ["--","本校"]
        case .Keiou: return ["--","三田キャンパス","日吉キャンパス","矢上キャンパス","信濃町キャンパス","湘南藤沢キャンパス","芝共立キャンパス","新川崎タウンキャンパス","殿町タウンキャンパス","鶴岡タウンキャンパス","浦和共立キャンパス","慶応丸の内シティキャンパス","慶応大阪シティキャンパス"]
        case .Keisenjogakuen: return ["--","本校"]
        case .Kougakuin: return ["--","新宿キャンパス","八王子キャンパス"]
        case .Kokugakuin: return ["--","渋谷キャンパス","たまプラーザキャンパス"]
        case .Kokusaikirisutokyo: return ["--","本校"]
        case .Kokushikan: return ["--","世田谷キャンパス","町田キャンパス","多摩キャンパス","国士舘楓の社キャンパス"]
        case .Kodomokyoikuhousen: return ["--","本校"]
        case .Komazawa: return ["--","駒沢キャンパス","深沢キャンパス","玉川キャンパス"]
        case .Komazawajoshi: return ["--","本校"]
        case .Sangyonouritsu: return ["--","自由ヶ丘キャンパス","湘南キャンパス","代官山キャンパス"]
        case .Jissenjoshi: return ["--","日野キャンパス","渋谷キャンパス"]
        case .Shibaurakougyo: return ["--","芝浦キャンパス","野洲キャンパス","大宮キャンパス"]
        case .Juntendo: return ["--","本郷・お茶の水キャンパス","さくらキャンパス","浦安キャンパス","三島キャンパス"]
        case .Jochi: return ["--","四谷キャンパス","目白聖母キャンパス","石神井キャンパス","秦野キャンパス","大阪サテライトキャンパス"]
        case .Johoukeieiinobesyonsenmonsyoku: return ["--","墨田キャンパス","竹芝サテライトオフィス"]
        case .Syowa: return ["--","旗の台キャンパス","洗足キャンパス","横浜キャンパス","富士吉田キャンパス"]
        case .Syowajoshi: return ["--","世田谷キャンパス","ボストン(海外キャンパス)"]
        case .Syowayakka: return ["--","本校"]
        case .Joshibijutsu: return ["--","相模原キャンパス","杉並キャンパス"]
        case .Shiraumegakuen: return ["--","本校"]
        case .Shirayurijoshi: return ["--","本校"]
        case .Suginohukusyoku: return ["--","目黒キャンパス","日野キャンパス"]
        case .Seikei: return ["--","本校"]
        case .Seijo: return ["--","本校"]
        case .Seishinjoshi: return ["--","本校"]
        case .Seisenjoshi: return ["--","本校"]
        case .Seirukakokusai: return ["--","本校"]
        case .Sensyu: return ["--","神田キャンパス","生田キャンパス","サテライトキャンパス"]
        case .Souka: return ["--","本校"]
        case .Taisyo: return ["--","本校"]
        case .Daitobunka: return ["--","板橋キャンパス","東松山キャンパス"]
        case .Takachiho: return ["--","杉並キャンパス"]
        case .Takusyoku: return ["--","文京キャンパス","八王子国際キャンパス"]
        case .Tama: return ["--","多摩キャンパス","湘南キャンパス","品川サテライト","田村学園目黒ビル","九段サテライト"]
        case .Tamagawa: return ["--","本校"]
        case .Tamabijutsu: return ["--","八王子キャンパス","上野毛キャンパス"]
        case .Chuo: return ["--","多摩キャンパス","市ヶ谷キャンパス","後楽園キャンパス","市谷田町キャンパス"]
        case .Tsudajuku: return ["--","小平キャンパス","千駄ヶ谷キャンパス"]
        case .Teikyo: return ["--","板橋キャンパス","八王子キャンパス","宇都宮キャンパス","福岡キャンパス","霞ヶ関キャンパス"]
        case .Teikyokagaku: return ["--","千住キャンパス","東京西キャンパス"]
        case .Teikyoheisei: return ["--","池袋キャンパス","中野キャンパス","千葉キャンパス","ちはら台キャンパス"]
        case .Dejitaruhollywood: return ["--","駿河台キャンパス"]
        case .Tokai: return ["--","湘南キャンパス","高輪キャンパス","伊勢原キャンパス","札幌キャンパス","代々木キャンパス","清水キャンパス","熊本キャパス"]
        case .Tokyoariakeiryo: return ["--","本校"]
        case .Tokyoika: return ["--","本校"]
        case .Tokyoiryogakuin: return ["--","本校"]
        case .Tokyoiryohoken: return ["--","国立病院機構立川キャンパス","世田谷キャンパス","五反田キャンパス","国立病院機構キャンパス"]
        case .Tokyoongaku: return ["--","中目黒・代官山キャンパス","池袋キャンパス"]
        case .Tokyokasei: return ["--","は狭山キャンパス","板橋キャンパス"]
        case .Tokyokaseigakuin: return ["--","千代田三番町キャンパス","町田キャンパス"]
        case .Tokyokeizai: return ["--","国分寺キャンパス","武蔵野村山キャンパス"]
        case .Tokyokouka: return ["--","八王子キャンパス","蒲田キャンパス"]
        case .Tokyokougei: return ["--","厚木キャンパス","中野キャンパス"]
        case .Tokyoshika: return ["--","水道橋キャンパス","市川キャンパス","千葉キャンパス"]
        case .Tokyojikeikaiika: return ["--","西新橋キャンパス","国領キャンパス"]
        case .Tokyojunshin: return ["--","本校"]
        case .Tokyojoshi: return ["--","本校"]
        case .Tokyojoshiika: return ["--","河田町キャンパス","掛川キャンパス"]
        case .Tokyojoshitaiiku: return ["--","本校"]
        case .Tokyoshingaku: return ["--","本校"]
        case .Tokyoseiei: return ["--","本校"]
        case .Tokyoseitoku: return ["--","十条台キャンパス","八千代キャンパス"]
        case .Tokyozoukei: return ["--","本校"]
        case .Tokyodenki: return ["--","東京千住キャンパス","埼玉鳩山キャンパス","千葉ニュータウンキャンパス"]
        case .Tokyotoshi: return ["--","世田谷キャンパス","横浜キャンパス","等々力キャンパス","王禅寺キャンパス"]
        case .Tokyonougyo: return ["--","世田谷キャンパス","厚木キャンパス","北海道オホーツクキャンパス"]
        case .Tokyohukushi: return ["--","池袋キャンパス","伊勢崎キャンパス","王子キャンパス","名古屋キャンパス"]
        case .Tokyofuji: return ["--","本校"]
        case .Tokyohokeniryosenmonsyoku: return ["--","本校"]
        case .Tokyomirai: return ["--","堀切キャンパス"]
        case .Tokyoyakka: return ["--","本校","千代田サテライトキャンパス"]
        case .Tokyorika: return ["--","神楽坂キャンパス","葛飾キャンパス"]
        case .Toho: return ["--","大森キャンパス","習志野キャンパス"]
        case .Tohogakuen: return ["--","仙川キャンパス","調布キャンパス","富山キャンパス"]
        case .Toyo: return ["--","白山キャンパス","赤羽台キャンパス","朝霞キャンパス","川越キャンパス","板倉キャンパス","大手町サテライトキャンパス"]
        case .Nisyogakusya: return ["--","九段キャンパス","柏キャンパス","AKIBA Lab."]
        case .Nihonsekijuujikango: return ["--","大宮キャンパス","広尾キャンパス","武蔵野キャンパス"]
        case .Nihon: return ["--","日本大学会館","桜門会館","江古田キャンパス","所沢キャンパス","駿河台キャンパス","船橋キャンパス","津田沼キャンパス","実籾キャンパス"]
        case .Nihonika: return ["--","武蔵境キャンパス","千駄木キャンパス"]
        case .Nihonshika: return ["--","東京キャンパス","新潟キャンパス"]
        case .Nihonsyakaijigyo: return ["--","清瀬キャンパス","文京キャンパス"]
        case .Nihonjuuiseimeikagaku: return ["--","板橋キャンパス","東松山キャンパス","緑山キャンパス"]
        case .Nihonjoshi: return ["--","目白キャンパス","西生田キャンパス"]
        case .Nihonjoshitaiiku: return ["--","本校"]
        case .Nihontaiiku: return ["--","東京・世田谷キャンパス","横浜・健志台キャンパス"]
        case .Nihonbunka: return ["--","八王子キャンパス"]
        case .Bunkagakuen: return ["--","本校"]
        case .Bunkyogakuin: return ["--","本郷キャンパス","ふじみ野キャンパス"]
        case .Housei: return ["--","市ヶ谷キャンパス","多摩キャンパス","小金井キャンパス"]
        case .Hoshiyakka: return ["--","本校"]
        case .Musashi: return ["--","江古田キャンパス"]
        case .Musashino: return ["--","有明キャンパス","武蔵野キャパス","鷹サテライト教室","千代田サテライトキャンパス"]
        case .Musashinoongaku: return ["--","江古田キャンパス","入間キャンパス"]
        case .Musashinobijutu: return ["--","鷹の台キャンパス","市ヶ谷キャンパス"]
        case .Meiji: return ["--","駿河台キャンパス","和泉キャンパス","生田キャンパス","中野キャンパス"]
        case .Meijigakuin: return ["--","白金キャンパス","横浜キャンパス"]
        case .Meijiyakka: return ["--","清瀬キャンパス"]
        case .Meisei: return ["--","本校"]
        case .Yamazakidoubutsukango: return ["--","南大沢キャンパス"]
        case .Rikkyo: return ["--","池袋キャンパス","新座キャンパス"]
        case .Rissyo: return ["--","品川キャンパス","熊谷キャンパス"]
        case .Ruterugakuin: return ["--","本校"]
        case .Wako: return ["--","本校"]
        case .Waseda: return ["--","早稲田キャンパス","戸山キャンパス","西早稲田キャンパス","喜久井町キャンパス","日本橋キャンパス","東伏見キャンパス","所沢キャンパス","本庄キャンパス","北九州キャンパス"]
        case .Azabu: return ["--","本校"]
        case .Kanagawa: return ["--","横浜キャンパス","湘南ひらつかキャンパス","みなとみらいキャンパス"]
        case .Kanagawakouka: return ["--","本校"]
        case .Kanagawasika: return ["--","本校"]
        case .Kamakurajoshi: return ["--","大船キャンパス"]
        case .Kantogakuin: return ["--","横浜・金沢八景キャンパス","横浜・金沢文庫キャンパス","湘南・小田原キャンパス"]
        case .Sagamijoshi: return ["--","本校"]
        case .Syoin: return ["--","厚木森の里キャンパス","厚木ステーションキャンパス","湘南キャンパス","下北沢キャンパス","北沢ステーションキャンパス"]
        case .Toyoeiwajogakuin: return ["--","本校"]
        case .Nihoneiga: return ["--","白山キャンパス","新百合ヶ丘キャンパス"]
        case .Ferisujogakuin: return ["--","緑園キャンパス","山手キャンパス"]
        case .Yokohamasyouka: return ["--","つるみキャンパス","みどりキャンパス"]
        case .Yokohamasouei: return ["--","本校"]
        case .Yokohamabijutu: return ["--","本校"]
        case .Yokohamayakka: return ["--","本校"]
        }
    }
}
